### ISSUE TITLE
Snippets are missing in v3

### ISSUE THREAD

**Issue by amitaibu** [jhedstrom/drupalextension#110]
```Gherkin
--- Snippets for the following steps in the default suite were not generated (check your configuration):

    Given I visit "/user"
    Then I should see "Log in"
```

This seems like a "regression" from previous version, where it provided the snippet. Not sure yet how to enable this feature.

**Comment by NarjesWeslati** [comment]
did you fix that issue ? I have the same problem and I can't figure out how to enale it. thx :)

**Comment by jhedstrom** [comment]
In Behat 3 snippets are no longer printed out. Instead, you implement `SnippetAcceptingContext` in whichever context you want snippets to be automatically appended to. See https://github.com/Behat/Behat/issues/652#issue-47512619 as noted above.

**Comment by jhedstrom** [comment]
Also see https://behat-drupal-extension.readthedocs.org/en/3.0/localinstall.html

**Comment by amitaibu** [comment]
also, @NarjesWeslati [hedley](https://github.com/Gizra/generator-hedley) will scaffold a working and configured Behat v.3 for you

**Comment by jhedstrom** [comment]
@amitaibu hedley looks awesome!

**Comment by amitaibu** [comment]
Thanks - it needs some more public relation so feel free to help spread the word ;)

‫ב-5 במרץ 2015, בשעה 22:15, ‏Jonathan Hedstrom <notifications@github.com> כתב/ה:‬
