### ISSUE TITLE
From the docs: features/bootstrap/FeatureContext.php is for testing the Drupal Extension itself

### ISSUE THREAD

**Issue by amitaibu** [jhedstrom/drupalextension#112]
So where should my FeatureContext.php exist? And how should I add it (i guess through ``context`` in ``behat.yml`` -- but an example with namespaces would be appreciated)

**Comment by eliza411** [comment]
I think I've added what was requested. If not, please reopen with concrete suggestions! Thanks for taking time to help improve this.
