### ISSUE TITLE
Which api_driver is the fastest?

### ISSUE THREAD

**Issue by greggles** [jhedstrom/drupalextension#119]
I wanted to add a note on [the driver comparison](http://behat-drupal-extension.readthedocs.org/en/latest/drivers.html) about which one is faster. The [Drupal API driver](http://behat-drupal-extension.readthedocs.org/en/latest/drupalapi.html) says that it is faster but in a quick local test that covered 8 scenarios and 182 steps it took 3m49.735s with api_driver: "drush" and 4m2.933s with api_driver: "drupal". I wasn't strict about running this in an isolated environment and the difference isn't huge (~5%) but...is there a definitive sense of which one is faster? :)

**Comment by jhedstrom** [comment]
Closing this out for now.

**Comment by greggles** [comment]
I had forgotten about this issue.

There's subsequently been a pretty good conversation on this topic at https://groups.drupal.org/node/460263
