### ISSUE TITLE
Cannot verify if a menu is present.

### ISSUE THREAD

**Issue by dutchiexl** [jhedstrom/drupalextension#132]
I want to write a test to check if a menu is present on my homepage. The content (links) inside the menu should not be important as they are dynamic. How should I do this. Is there a need for more mappings ?

**Comment by jhedstrom** [comment]
You could do a number of things. One would be a custom step definition:

```php
/**
 * @Given I see my menu
 */
public function assertMenu() {
  $page = $this->getPage();
  if (!$page->find('css', '#my-menu-id')) {
   throw new Exception('Menu does not exist on the page');
  }
}
```

You could also go the route of targetting a hidden heading in the menu (most menus output by core have this for accessibility IIRC). That way you could use existing steps:

```gherkin
Then I should see the heading 'my menu' in the 'left sidebar'
```
