### ISSUE TITLE
Fail test when a notice, warning or exception occurs in a request

### ISSUE THREAD

**Issue by pfrenssen** [jhedstrom/drupalextension#143]
One of the features of Simpletest is that it tracks if any PHP errors occured in the browser requests and will fail the test if needed. This is incredibly helpful when developing since the test output will show the errors along with a backtrace when they occur.

Currently we do not have this in the Drupal Extension. The only way to do this currently is by checking if  any error messages are displayed on the screen. That is however a poor solution since error logging might be disabled and we do not get any additional information like backtraces.

I've looked at how this is currently done in Simpletest:
- A special user agent is used for doing the Curl requests. This user agent starts with 'simpletest' and followed by a series of number indicating the test run. See `drupal_valid_test_ua()`.
- If this user agent is present and validated the request will be marked as being a "child site" test request (ref `_drupal_bootstrap_database()` in Drupal 7, and `DrupalKernel::bootEnvironment()` in Drupal 8).
- `_drupal_log_error()` will output the errors and backtraces in special `X-Drupal-Assertion` HTTP headers. These are then picked up by Simpletest.

All this functionality is hard coded to Simpletest's behaviour at the moment. We cannot hook into it in any way to add additional user agents or use our own logic to mark a "child site test request". This means that we might have to try to mimic Simpletest's behaviour which can be rather challenging.

In [Issue #2232861: Create BrowserTestBase for web-testing on top of Mink](https://www.drupal.org/node/2232861) they are also mimicking Simpletest. Some additional code is added in that issue that will allow to set a cookie with the user agent used. It is unlikely this will ever be added to D7 though.

What would be a good first step for implementing this?

**Comment by jhedstrom** [comment]
There's a broken link in the docs that used to point at a way to do this with `@beforeSuite` and `@afterScenario` hooks by querying the watchdog table. I found a mirror of it here: http://mzlizz.mit.edu/godelcomau-use-behat-track-down-php-notices-they-take-over-your-drupal-site-forever

**Comment by pfrenssen** [comment]
Thanks! That looks like an interesting approach. It is not bullet proof though since it doesn't log which test is responsible for the page request, so it would cause false positives when running multiple tests in parallel. It's still a track very worthwhile of investigation.

If [Issue #2232861: Create BrowserTestBase for web-testing on top of Mink](https://www.drupal.org/node/2232861) gets in we can probably support this out of the box on Drupal 8, but for Drupal 7 it seems we will need to enable a contributed module to communicate the error messages.

I'm also thinking that it would be interesting if this was configurable, so that people can either choose the error level at which a test should fail, or opt to switch it off entirely.

How do you feel about failing on PHP errors and notices? Do you think this should be an integral part of BDE? I can work on this as part of my day job, I am introducing Behat at my employer and one of our requirements is that our tests should detect PHP errors.

**Comment by jhedstrom** [comment]
I think making this configurable, but defaulting to failing on PHP errors and warnings makes sense. Some folks might chose to disable that behavior entirely, while others might go the other way and fail all the way down to notices.

Thanks for all the work you've been putting into this!

**Comment by pfrenssen** [comment]
I'm currently working on issue #2232861, if that is in then this will be much easier to implement.

**Comment by ademarco** [comment]
Following on d.o. +1!

**Comment by pfrenssen** [comment]
I'm going to pick this back up. [Issue #2232861: Create BrowserTestBase for web-testing on top of Mink](https://www.drupal.org/node/2232861) has been merged ages ago.

I will start by exploring if it is possible to use the mechanism introduced in #2232861 to detect whether failures occur. Similar to Behat, BrowserTestBase uses Mink to request pages to test. It sets a cookie `SIMPLETEST_USER_AGENT` that will instruct Drupal to expose PHP errors in the HTTP headers. Because this is sensitive data this will check if a key file exists in `sites/simpletest/$prefix/.htkey`. The `$prefix` is the database prefix that is used in Simpletests and Browsertests to have an isolated database environment. We won't be using this database prefix, but from a first glance at the code this doesn't seem to be a strict requirement.

The relevant functions dealing with this in Drupal 8 are `drupal_valid_test_ua()` and `drupal_generate_test_ua()`.

This functionality is only unlocked for external test systems such as Mink in Drupal 8. To support this in Drupal 7 we will have to provide a contrib module that needs to be enabled in the test site to expose the same data. Or alternatively we can backport this from D8 and provide it as a core patch.

**Comment by pfrenssen** [comment]
This will require some changes to the MinkExtension, similar to what was discussed in #133. Since all requests pass through Mink we should be able to set the cookie before any request is done.

**Comment by pfrenssen** [comment]
I posted a work in progress of a first implementation, but the approach has been rejected: https://github.com/Behat/MinkExtension/pull/226

@stof, the maintainer of MinkExtension, proposes two possible solutions in that pull request:

> * identify all methods of a driver which can trigger a request (the list is given above for the case of non-JS-enabled drivers) and create a driver triggering some logic in them (hardcoded logic, or triggering an event, or triggering a hook if you really need to have contexts able to react to it but it would be weird) and delegating to the actual driver. Your own behat extension could then manipulate the container (in process) to wrap drivers into your own driver.
> * decide that you only care about the GoutteDriver, and hook at the guzzle level to do it (much easier as they already trigger event for requests, so you would only have to register a listener in the guzzle client by using a Behat extension to change the container)

While the GoutteDriver is likely to be the most used we need to support all drivers. I'm a bit hesitant to implement our own driver inside the DrupalExtension since this functionality would benefit other projects as well. I'm going to investigate if there is a way to do this in Mink somehow.

**Comment by stof** [comment]
@pfrenssen as I explained in the MinkExtension discussion, doing it for all drivers is not possible: drivers supporting JS may trigger new requests on almost any interaction (or even without doing any interaction in case of using ``setTimeout`` to trigger them later btw).

**Comment by pfrenssen** [comment]
@stof so Mink itself has no way of knowing when a request occurs by drivers like Selenium and PhantomJS? They don't communicate that? That seems like a huge gap in their functionality.

**Comment by pfrenssen** [comment]
I discussed this a couple of days ago with @dawehner and @jhedstrom on IRC.

The approach of trying to intercept all requests is wrong from a BDD perspective. After all if we are testing the _behaviour_ of an application, then we don't care about how a certain behaviour works behind the scenes. Whether an application does an AJAX call or uses its own internal logic to achieve a certain result doesn't ultimately matter for the end user.

It is important to keep in mind when writing tests that a request can happen in the background at any moment and that we will not be notified when it happens. This basically precludes us from mixing direct API calls and browser requests. Once we do a browser request this might trigger subsequent requests in javascript, so anything that is statically cached in the Drupal instance we use for direct API calls might be invalidated at any given time.

In theory this would mean that in an `@api` test we should exclusively use direct API calls, and no browser requests, but in practice it will be fine to use `@api` to prepare the test (e.g. in the `Background` part) and then rely exclusively on browser requests for the assertions.

This also means that we cannot rely on Behat tests catching each and every PHP error that might occur, we have to complement it with unit tests / web tests / kernel tests. But that's fine I guess, use the right tool for the job.

To move forward with this, let's try to catch as much as we can. We can use the same trick as is being done in the JavascriptTestBase issue: do an initial request setting the cookie that will unlock the PHP error disclosure, and rely on the fact that the cookie will persist in the browser.

**Comment by pfrenssen** [comment]
I think this should be closed, as described above Behat is not suitable for testing PHP code. We should use PHPUnit for that. Behat is only suitable for testing user behavior.

**Comment by dawehner** [comment]
+1

**Comment by deviantintegral** [comment]
This makes sense, however for real-world sites there are many times when changes cause notices and errors outside of your custom code. Unit tests aren't going to exercise theme preprocess hooks, or the notice could be due to an external module. Writing specific scenarios to test for PHP errors doesn't make sense, but knowing that errors have been logged for a given change is pretty valuable.

Here's the `@AfterStep` scenario we're using:

```php
  /**
   * Fail any scenario if a PHP error is logged.
   *
   * Note this depends on the Drupal database log and it's settings.
   *
   * @AfterStep
   */
  public function thereAreNoPhpErrorsLogged() {
    $result = db_select('watchdog', 'w')
      ->fields('w', [])
      ->condition('w.type', 'php', '=')
      ->execute();

    $errors = [];
    foreach ($result as $entry) {
      $variables = unserialize($entry->variables);
      $errors[] = new \Drupal\Component\Render\FormattableMarkup($entry->message, $variables);
    }

    if (!empty($errors)) {
      // Delete any errors so the next scenario can run.
      db_delete('watchdog')
        ->condition('type', 'php')
        ->execute();
      throw new \Exception("PHP Errors were logged:\r\n" . implode("\r\n", $errors));
    }
  }
```
