### ISSUE TITLE
Creating nodes has problem with Handlers

### ISSUE THREAD

**Issue by dutchiexl** [jhedstrom/drupalextension#146]
<code>Warning: Invalid argument supplied for foreach() in /Library/WebServer/Documents/cegeka/ftaworld/vendor/drupal/drupal-driver/src/Drupal/Driver/Fields/Drupal7/DefaultHandler.php line 22</code>

The error is generated by this code:
<code>foreach ($values as $value) {
      $return[LANGUAGE_NONE][] = array('value' => $value);
    }</code>

because not all values are arrays.

I changed the code to this: <code>foreach ((array)$values as $value) { </code> in all handlers which fixed the problem, but I am still having an issue with the body field, which doesn't seem to be saved.

**Comment by dutchiexl** [comment]
The body field has a problem for me because I don't accept language undefined. I am going to rework it tommorow so that it is possible to add languages.

**Comment by ademarco** [comment]
Yes, indeed, the next step for field handlers in D7 is to make them language aware. Could you share the scenario that generates the warning?

**Comment by dutchiexl** [comment]
<code>  @api
  Scenario: When a news item is created, I should be able to see it in the overview
    Given I created a "News" content:
      | title | News feature: News item 1 |
      | body        | This is a news item       |
      | field_date  | 2018-02-25 07:45:45       |
    And I break
    And I am on "/news"
    Then I should see the link "News feature: News item 1" in the "main" region</code>

**Comment by ademarco** [comment]
Is ```Given I created a "News" content:``` a custom step definition?

**Comment by dutchiexl** [comment]
Yes it is, it is a copy of Given I am viewing ... but without the goto

**Comment by jhedstrom** [comment]
Is this still an issue? The corresponding [issue](https://github.com/jhedstrom/DrupalDriver/pull/19) was closed without being merged.

**Comment by jhedstrom** [comment]
Closing. Feel free to re-open if this is still happening.
