### ISSUE TITLE
Filesystem wrappers behave oddly during tests

### ISSUE THREAD

**Issue by IslandUsurper** [jhedstrom/drupalextension#161]
I have tests that generate files in the private filesystem, and while everything works fine, I have noticed that it places them relative to wherever I run behat, which is usually not the Drupal root in my setup.

While unexpected, I think it might be beneficial because it will make cleaning up those files easier after the tests run. I'm just wondering if something ought to be done to control where the files get saved instead of relying on the current directory.

**Comment by jhedstrom** [comment]
A [recent change was made to the DrupalDrivers](https://github.com/jhedstrom/DrupalDriver/pull/25) that keeps execution in the Drupal root (it previously switched back and forth between Behat and Drupal roots). Are you running the latest version of those?

**Comment by IslandUsurper** [comment]
No, I am not. That's what I was looking for, though. I guess I have to clean up those files the hard way now.

**Comment by jhedstrom** [comment]
Depending on how the files are created, you might be able to mimic the automatic cleanup of nodes, users, roles, and terms that the [`RawDrupalContext`](https://github.com/jhedstrom/drupalextension/blob/master/src/Drupal/DrupalExtension/Context/RawDrupalContext.php#L153-L163) does, using `@afterScenario` hooks.
