### ISSUE TITLE
Step not comparing attribute against :value argument

### ISSUE THREAD

**Issue by bt-eric** [jhedstrom/drupalextension#162]
For the step
`@Then I( should) see the :tag element with the :attribute attribute set to :value in the :region( region)`
the assertRegionElementAttribute function will return TRUE if it finds the attribute. It does not compare the attribute value against the :value argument. This is due to the break statement exiting the for loop before the code that checks the value is executed.

**Comment by jhedstrom** [comment]
This has been merged. Thanks again!
