### ISSUE TITLE
Accessing the currently logged in user in subsequent steps

### ISSUE THREAD

**Issue by njbarrett** [jhedstrom/drupalextension#173]
I am having an issue trying to create a custom step definition to "assume" some content exists created with my account.

```
  Scenario: Testing adding content
    Given I am logged in as a user with the "content author" role
    And I have created an article using my account
    When I go to "admin/content"
    Then I should see an article
```

(note this isn't my exact test, just an example)

My custom step definition inside FeatureContext:

```
  /**
   * @Given I have created an using my account
   */
  public function iHaveCreatedAnArticleUsingMyAccount() {
    var_dump($this->user);
    ...
  }
```

`var_dump($this->user)` returns `bool(false)`

Given that I have the step "I am logged in as...." before my custom step, shouldn't `$this->user` be set to the user created and logged in?

**Comment by claudiu-cristea** [comment]
@njbarrett, I'm having the same dilemma. How to access the logged in user. I need only the uid. Have you managed to find out how?

**Comment by claudiu-cristea** [comment]
What I did, I made FeatureContext to extend DrupalContext (changed also the use statement) and removed DrupalContext from `behat.yml`.

But I'm not sure that this is the right way...

**Comment by jhedstrom** [comment]
Extending `DrupalContext` is currently the only way to get access to those users and nodes created by the steps within. In future versions, I'd like to pull the users/nodes/terms created by each step back into the DrupalDriver, which is then shared across all contexts.

**Comment by jhedstrom** [comment]
The other way to get at these objects is to access the `DrupalContext` from your other contexts. See http://docs.behat.org/en/latest/cookbooks/context_communication.html.

**Comment by natgateway** [comment]
I was wondering what other objects DrupalRawContext cannot access and would need a similar workaround from above, as this is not currently in any of the documentation I've looked at. I'm very new to the drupal extension and behat in general, but I'd imagine trying to get the UID is a common need for those creating custom steps to test modules. While I'm glad this thread helped direct me toward the solution I was looking for (getting the UID), it left me a bit curious about what other objets RawDrupalContext vs. DrupalContext can and cannot access in the current drupal extension version, as the complexity of my custom steps is likely to increase and it would help a great deal if I could find some more information on this. Thanks for helping a newbie out :D

**Comment by jhedstrom** [comment]
@natgateway using the context communication approach linked above, you should be able to access any public methods/properties on any contexts that are loaded for a given scenario.
