### ISSUE TITLE
Incompatible with zombie driver?

### ISSUE THREAD

**Issue by MKorostoff** [jhedstrom/drupalextension#180]
I don't know that I understand this problem well enough to file a meaningful bug report (or even have confidence that this is the right issue queue), but the gist of this problem is that I can't get the Drupal extension and the Mink zombie driver to work in the same behat install.  I have tried *many* different version combinations but they all produce some variant on this error:

```javascript
Error "Cannot read property 'nodeType' of null" while executing code: var node,
    refs = [],
    result = browser.xpath("\/\/html\/descendant-or-self::body[@class and contains(concat(' ', normalize-space(@class), ' '), ' not-logged-in ')]");

while (node = result.iterateNext()) {
    if (node.nodeType !== 10) {
        pointers.push(node);
        refs.push(pointers.length - 1);
    }
}
stream.end(JSON.stringify(refs)); (Behat\Mink\Exception\DriverException)

```

Here's a screen shot of the same:

![zombie](https://cloud.githubusercontent.com/assets/1197335/8245862/d350a924-1602-11e5-830a-f7f6d807178d.png)

I know that's not super helpful, and sorry if this is in the wrong place, just not sure I understand this enough to diagnose it further.

**Comment by jhedstrom** [comment]
I just filed https://github.com/minkphp/MinkZombieDriver/issues/132. I think perhaps the driver isn't compatible with the latest version. Using 2.5.1 (`npm install -g zombie@^2.5`) has it working for me.

**Comment by jhedstrom** [comment]
I'm also adding zombie testing in #181.

**Comment by MKorostoff** [comment]
Thanks!  Yeah, that seems like the right queue now that I look at it more closely.  Shall I close this issue, or would you rather keep it open until minkphp/MinkZombieDriver#132 is resolved?

**Comment by jhedstrom** [comment]
We can close for now I think.
