### ISSUE TITLE
Add support for named field columns

### ISSUE THREAD

**Issue by pfrenssen** [jhedstrom/drupalextension#182]
It would be great to be able to use named field columns for tests. This would allow us to test complex fields such as AddressField without having to write custom code:

```
Scenario: Test address field
  Given I am logged in as a user with the "administrator" role
  When I am viewing a "post" content:
    | title                | Post title                                                                       |
    | field_post_address   | country: BE - locality: Brussel - thoroughfare: Louisalaan 1 - postal_code: 1000 |
  Then I should see "Post title"
  And I should see "Belgium"
  And I should see "Brussel"
  And I should see "1000"
  And I should see "Louisalaan 1"
```

The sister issue in DrupalDriver is [#40: Add support for field columns to the default field handler](https://github.com/jhedstrom/DrupalDriver/pull/40).

**Comment by pfrenssen** [comment]
I started working on this in my fork at https://github.com/pfrenssen/drupalextension/commits/field-columns.

I have implemented the functionality and test coverage for Drupal 7. I have used the AddressField module for this.

I'm now stuck adding test coverage for Drupal 8 since the AddressField module has not been officially ported yet (there is an unofficial port by Webflo). I am not aware of any other Drupal 8 modules that add complex fields.

How shall we proceed? Shall I create a custom field type in the Behat Test module and use that?

**Comment by ademarco** [comment]
A custom field type sounds like a great idea to me, we can mock basic Address Fields functionalities until the D8 module is ported.

**Comment by ademarco** [comment]
How about moving sub-fields name into the column names? It could improve readability, for example:

```gherkin
Scenario: Test address field
  Given I am logged in as a user with the "administrator" role
  When I am viewing a "post" content:
    | title                            | Post title   |
    | field_post_address:country       | BE           |
    | field_post_address:locality      | Brussel      |
    | field_post_address:thoroughfare  | Louisalaan 1 |
    | field_post_address:postal_code   | 1000         |
```

We would benefit for this kind of notation particularly when creating more than one node at the same time, like instead of having:

```gherkin
Scenario: Test address field
  Given I am logged in as a user with the "administrator" role
  And "post" content:
    | title     | field_post_address                                                                       |
    | Title 1   | country: BE - locality: Brussel - thoroughfare: Louisalaan 1 - postal_code: 1000         |
    | Title 2   | country: IT - locality: Rome - thoroughfare: Via dei Fori Imperiali 1 postal_code: 12345 |
```

We would have:

```gherkin
Scenario: Test address field
  Given I am logged in as a user with the "administrator" role
  And "post" content:
    | title     | field_post_address:country | field_post_address:locality | field_post_address:thoroughfare | field_post_address:postal_code |
    | Title 1   | BE                         | Brussel                     | Louisalaan 1                    | 1000                           |
    | Title 2   | IT                         | Rome                        | Via dei Fori Imperiali 1        | 12345                          |
```

Which kind of makes it a little more legible, what do you think?

**Comment by ademarco** [comment]
And to make it less verbose we could also use a kind of convention starting subsequent sub-fields with ":", until the next field name is actually specified, so like:

```gherkin
Scenario: Test address field
  Given I am logged in as a user with the "administrator" role
  And "post" content:
    | title     | field_post_address:country | :locality | :thoroughfare            | :postal_code | field_link:title | :url               |
    | Title 1   | BE                         | Brussel   | Louisalaan 1             | 1000         | Link title 1     | http://example.com |
    | Title 2   | IT                         | Rome      | Via dei Fori Imperiali 1 | 12345        | Link title 2     | http://example.com |
```

**Comment by pfrenssen** [comment]
Great idea!

**Comment by pfrenssen** [comment]
I have added support for the following use cases to my branch for Drupal 7:

```
  Scenario: Test various node field handlers in Drupal 7
    When I am viewing a "post" content:
      | field_post_address   | country: BE - locality: Brussel - thoroughfare: Louisalaan 1 - postal_code: 1000 |

  Scenario: Test alternative syntax for named field columns on node content
    When I am viewing a "post" content:
      | field_post_address:country      | FR                          |
      | field_post_address:locality     | Paris                       |
      | field_post_address:thoroughfare | 1 Avenue des Champs Elysées |
      | field_post_address:postal_code  | 75008                       |

  Scenario: Test shorthand syntax for named field columns on node content
    When I am viewing a "post" content:
      | field_post_address:country | GB              |
      | :locality                  | London          |
      | :thoroughfare              | 1 Oxford Street |
      | :postal_code               | W1D 1AN         |

  Scenario: Test multivalue fields with named field columns on node content
    When I am viewing a "post" content:
      | field_post_address:country | IT, JP                                 |
      | :locality                  | Milan, Tokyo                           |
      | :thoroughfare              | 1 Corso Buenos Aires, Shibuya Crossing |
      | :postal_code               | 20124, 150-0040                        |
```

@jhedstrom, @ademarco any thoughts before I continue?

1. I was wondering if we should still support my original idea of the inline column names. Having the two use cases adds some complexity to the code but I think it might still be useful in case of simple fields, for example:
   `| Link | url: http://www.drupal.org - title: Drupal |`
2. Is there a way that I can test if the exceptions are thrown correctly if someone would write an invalid test scenario? For example if this is used as the first line of the table it should throw an exception since we cannot determine the field name:
   `| :country | BE |`
3. I would like some input on the delimiter that I use for the inline case. I'm using ": " now, a double colon followed by a space. The idea is to still allow people to use a double colon in their strings. But I can imagine this causing confusion because this is can be used in strings:
   `| title | Breaking: Obama caught shoplifting |`
   Of course the same goes for the ' - ' delimiter for multivalue fields. Maybe I'm overthinking this and we should just provide some good documentation.

Next steps would be to add D8 support (which involves a fake field type) and to add documentation.

**Comment by ademarco** [comment]
Nice stuff! Answering your points:

1. I think it does no arm to keep that notation since it might turn useful in certain cases, like the one you outline.
2. Not sure where the right place could be.
3. I think we can assume certain characters to be used as separators, like ```:```, ```,```, etc. so providing a good documentation would probably be enough. Or we can also support something like this:

```gherkin
  Scenario: Test multivalue fields with named field columns on node content
    When I am viewing a "post" content:
      | field_post_address:country | IT                     | JP               |
      | :locality                  | Milan                  | Tokyo            |
      | :thoroughfare              | 1 Corso Buenos Aires   | Shibuya Crossing |
      | :postal_code               | 20124                  | 150-0040         |
``` 

But it would be maybe unnecessarily overcomplicated.

**Comment by jhedstrom** [comment]
One thing I would want to make sure is still possible would be to alias each part of the path to whatever one wants using [`@Transform`](http://docs.behat.org/en/latest/guides/2.definitions.html#step-argument-transformations).

This way people could, for instance, instead of using `field_post_address:country` in their actual scenario, call it simply `Country` and then do the transform in code.

Aside from that note, this looks like a great direction!

**Comment by pfrenssen** [comment]
Thanks for the feedback! I will make sure to add good documentation for the separators. I've also added a testcase for the @Transform concept, I didn't yet know of this, thanks for mentioning it! This will come in very handy :)

Regarding this example:
```
Scenario: Test multivalue fields with named field columns on node content
    When I am viewing a "post" content:
      | field_post_address:country | IT                     | JP               |
      | :locality                  | Milan                  | Tokyo            |
      | :thoroughfare              | 1 Corso Buenos Aires   | Shibuya Crossing |
      | :postal_code               | 20124                  | 150-0040         |
```

I don't think we can split multi value fields into separate table columns since this would only work if we have the same number of values for every field in the table. For example the `title` field is single value, but the address fields might be multi value. We would end up with empty cells.

**Comment by ademarco** [comment]
@pfrenssen Right, of course!

**Comment by pfrenssen** [comment]
This is 99% finished but I'm currently blocked on #193. I am leaving on holiday soon and after that I will not have so much spare time since I am starting on a new side project.

It might be some weeks or even months until I can continue on this (unless #193 would get fixed within the next 2 days) so I wanted to get this code out in the meanwhile.

In the pull request I have also refactored the test coverage and test modules so that the test scenarios for D7 and D8 are now identical for as much as was possible. This is better proof that it works as intended.

**Comment by pfrenssen** [comment]
#193 has been merged, picking this back up.

**Comment by jhedstrom** [comment]
#196 has been merged. Thanks for all the work on this!

**Comment by generalconsensus** [comment]
@jhedstrom I don't see this mentioned in the docs, can you recommend where it should be added and I will gladly add a PR to fix this issue
