### ISSUE TITLE
Drupal 8 beta12 support question

### ISSUE THREAD

**Issue by mortenson** [jhedstrom/drupalextension#185]
Has anyone been using this with Drupal 8 beta12 (and more recent dev commits)? My behat test is failing with a new error, and the only change is the core Drupal version:

The test:
```
  @api
  Scenario: Create an article node
    Given I am logged in as a user with the "administrator" role
    When I am viewing an "article" content with the title "My article"
    Then I should see the heading "My article"
```

The error:
```
The "node" parameter was not converted for the path "/node/{node}" (route name:"entity.node.canonical") (Drupal\Core\Entity\EntityStorageException)
```

**Comment by brantwynn** [comment]
I believe this was unique to the install profile we were working with.  We had a system.site.yml file that was from beta11 in our config/install folder and it was causing portions of the site install to fail silently.

This can probably be closed unless others are also seeing issues.

**Comment by jhedstrom** [comment]
Thanks for the update.
