### ISSUE TITLE
Tests are failing since Drupal 8 updated Guzzle to 5.3.0

### ISSUE THREAD

**Issue by pfrenssen** [jhedstrom/drupalextension#193]
The Drupal 8 tests on the current master branch are failing because some interfaces have changed in the new Guzzle 5.3.0:

```
PHP Fatal error:  Declaration of GuzzleHttp\Client::send() must be compatible with GuzzleHttp\ClientInterface::send(GuzzleHttp\Message\RequestInterface $request) in /home/travis/build/pfrenssen/drupalextension/drupal/core/vendor/guzzlehttp/guzzle/src/Client.php on line 27
```

This is occurring because Behat needs Goutte, and Goutte needs Guzzle, so Guzzle is present in our autoloader. An older version of Guzzle is also present in Drupal 8 core, so when the D8 API functions are used they will invoke methods that are adhering to the older version, causing fatal errors to be thrown when an incompatible interface is encountered.

This is highlighting another problem: When Drupal 8 is bootstrapped in `DrupalDriver::getDrupalVersion()` the `autoload.php` of Drupal 8 is parsed, so we are actually loading two conflicting autoloaders, our own and Drupal's. This will cause conflicts when functions are redeclared, it is actually surprising that it worked up to now.

**Comment by pfrenssen** [comment]
I was mistaken, it was not an upstream release of Guzzle, but actually the update of Guzzle in Drupal 8 that causes the problem. See [Issue #2493911: Update guzzle, goutte and mink-goutte-driver to the latest release](https://www.drupal.org/node/2493911).

**Comment by Berdir** [comment]
Yes, I was confused a bit about 5.3.0

drupalextension should probably just update the requirements to get the same guzzle version? We had to update goutte and mink in core as well, so that should be possible.

**Comment by pfrenssen** [comment]
I tried that but got problems with functions being redeclared when Drupal's autoloader is parsed.

```
Fatal error: Cannot redeclare GuzzleHttp\Psr7\str() (previously declared in drupal-extension/vendor/guzzlehttp/psr7/src/functions.php:17) in /drupal/core/vendor/guzzlehttp/psr7/src/functions.php on line 39
```

What would be the best way to solve this permanently? It seems like we cannot rely on Drupal's autoloader.

We at least need to keep all shared dependencies in sync, which will work for now but not when we start supporting Drupal 9 in the future.

**Comment by pfrenssen** [comment]
If we cannot rely on Drupal's autoloader then we will have to create our own. The autoloader is invoked in DrupalDriver but we shouldn't hardcode any changes regarding to DrupalExtension in DrupalDriver. 
Shall we make an AutoloadEvent in DrupalDriver and a corresponding listener in DrupalExtension that can react and do the necessary changes to the list of files that are autoloaded?

I'm still not certain if this can be solved conclusively for future versions of Drupal when the dependencies will be different from the ones we have in D8 now. We might be able to do something with aliasing namespaces but that won't be easy.

**Comment by jhedstrom** [comment]
I'll take a look into how Drush is handling this.

**Comment by Berdir** [comment]
Note that this worked just fine for me. However, I'm using composer_manager and behat/guzzle is added/updated in core/vendor, so I only have a single vendor directory.

I'm still on drupalextension 1.x with a custom composer.json (that I started using a long time ago with the switch to guzzle 4 IIRC).

But I think you can solve this by updating the dependencies and making sure you end up with the same guzzle version.

**Comment by jhedstrom** [comment]
>But I think you can solve this by updating the dependencies and making sure you end up with the same guzzle version.
I'd prefer this approach for the time being (simple and quick). In the future we may still need to create our own autoloader.

**Comment by jhedstrom** [comment]
I wonder if instead of updating `composer.json` (which would then surely break php 5.4 and php 5.3 support), if we could instead document how to get the proper  versions, and then run something like

```
composer require guzzlehttp/guzzle
```

from `.travis.yml`? (Note, that command above isn't sufficient to install the proper libraries, as I get dependency errors related to goutte).

**Comment by slashrsm** [comment]
> However, I'm using composer_manager and behat/guzzle is added/updated in core/vendor, so I only have a single vendor directory.

I am using the same approach + requiring same version of behat/mink-goutte-driver as core works fine. Having only one vendor/ directory looks like the most reasonable choice to me.

**Comment by jhedstrom** [comment]
@Berdir or @slashrsm could you post the relevant versions (goutte, behat, etc) from the `composer.lock` file that allow this to work? I'd like to pursue my idea above of *not* adding these to `composer.json`, but rather document how to get everything working in project-specific `composer.json` files (and also in this project's `.travis.yml` file.

**Comment by jhedstrom** [comment]
Disregard, I just did a fresh install with the added Guzzle version required.

**Comment by pfrenssen** [comment]
Only updating the composer.json will not be enough, we will still get the fatal errors I mentioned above because functions will be redeclared. This happens in `ComposerAutoloaderInitDrupal8::getLoader()`:

```
    public static function getLoader()
    {
        ...
        $includeFiles = require __DIR__ . '/autoload_files.php';
        foreach ($includeFiles as $file) {
            composerRequireDrupal8($file);
        }

        return $loader;
    }
}

function composerRequireDrupal8($file)
{
    require $file;
}
```

When we bootstrap Drupal these `$includeFiles` will be loaded, but some of them define functions that are already defined, such as `GuzzleHttp\Psr7\str()`.

We will probably have to provide our own autoloader that will work around this.

**Comment by jhedstrom** [comment]
We have previously worked around the fatal errors of duplicated includes (see the links from #198 to react/promise--psr7 has a similar pending fix just waiting on a new release to be cut). It isn't ideal, but can at least buy us some time before we truly have to create a custom autoloader (drush will eventually be in a similar position).

**Comment by slashrsm** [comment]
I installed drupalextension in same docroot as Drupal using composer manager. This fixed duplicated errors fatals. It this approach fundamentally broken?

**Comment by pfrenssen** [comment]
@slashsrm  indeed it is possible to fix this in your Drupal site by ensuring you have a single vendor folder, by using composer manager or drupal-project.

This issue is about fixing the tests for DrupalExtension itself. We also use Behat for our own tests.

**Comment by slashrsm** [comment]
Ah... Thank you for clarification.

**Comment by brantwynn** [comment]
It looks like guzzle/psr7 cut release, but not 1.1.1, but 1.2.0: https://github.com/guzzle/psr7/releases

I think if they had called the 1.2 release as 1.1.1 it would have included the fix for https://github.com/guzzle/psr7/issues/27

**Comment by jeskew** [comment]
~1.1 should pull down 1.2. It means >=1.1;<2.0.

**Comment by jhedstrom** [comment]
Now we're just waiting on the corresponding core update https://www.drupal.org/node/2546272.

**Comment by pfrenssen** [comment]
Nice! That issue is already RTBC. Looks like a solution is very close now.

**Comment by nerdstein** [comment]
I don't think that solution fixes it. I applied the patch and tested. I still got the aforementioned error.

**Comment by brantwynn** [comment]
@nerdstein we had to use the patch for core but also update our /tests/composer.json to use the same versions of guzzle and psr7 as core

    "drupal/drupal-extension": "~3.0",
    "guzzlehttp/guzzle": "dev-master#1879fbe853b0c64d109e369c7aeff09849e62d1e",
    "guzzlehttp/psr7": "~1.2"

**Comment by nerdstein** [comment]
IT WORKS!

I'm going to drink a beer now...

**Comment by pfrenssen** [comment]
The upstream issue in core is RTBC. I'm going to see whether we can get the tests green again in pull request #202. I'll use a fork of Drupal core with the patch applied for testing.

I had a failure locally, I want to start looking into this so we can get this in asap when the upstream issue lands.

**Comment by pfrenssen** [comment]
https://www.drupal.org/node/2546272 is in!

**Comment by brantwynn** [comment]
@jhedstrom from an end user perspective, will we just want to stop pointing to a specific version of guzzle and psr7 in our /tests/composer.json (assuming the drupalextension will take care of the rest).  Is there anything else users will need to do?

**Comment by pfrenssen** [comment]
@brantwynn you should indeed be able to remove your dependencies on guzzle and psr7 now.

**Comment by jhedstrom** [comment]
@brantwynn you will still need to pin guzzle to `^6.0` for D8 I think. Here's a [link to the docs](https://behat-drupal-extension.readthedocs.org/en/master/localinstall.html) on that (but they aren't correctly compiling, so here's the raw doc (https://raw.githubusercontent.com/jhedstrom/drupalextension/master/doc/localinstall.rst)

**Comment by brantwynn** [comment]
Thanks, this is what we had changed it to- glad to see the docs confirmed
my assumption.

Additionally, I am not sure what changed in Travis CI (tests are passing
locally) but we're now seeing failures for steps like:
And I should see the "div" element with the "class" attribute set to "
recent-content" in the "middle" region

This happened only after we updated, but I believe it was coincidence, as a
revert did not fix the new failures. If there is a better place to get
support for that sort of thing than this thread, please lmk.

On Tue, Aug 25, 2015 at 2:47 PM, Jonathan Hedstrom <notifications@github.com
> wrote:

> @brantwynn <https://github.com/brantwynn> you will still need to pin
> guzzle to ^6.0 for D8 I think. Here's a link to the docs
> <https://behat-drupal-extension.readthedocs.org/en/master/localinstall.html>
> on that (but they aren't correctly compiling, so here's the raw doc (
> https://raw.githubusercontent.com/jhedstrom/drupalextension/master/doc/localinstall.rst
> )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhedstrom/drupalextension/issues/193#issuecomment-134716654>
> .
>



-- 

*Brant Wynn*Technical Lead, Presales | *Acquia
<http://www.acquia.com/?utm_source=Email&utm_medium=Signature&utm_content=Acquia.com&utm_campaign=Acquia%2BEmail%2BSignature>*
*O:* +1 617-588-9933 | *M:* +1 312-607-9430 | @brantwynn
<http://twitter.com>
Demo Drupal as an Enterprise-ready solution <http://acquia.com/downloads/df>

Start Building Drupal Sites on Acquia Cloud for Free!
<http://acquia.com/free>

**Comment by jhedstrom** [comment]
I think drupal.org was having some issues yesterday (the blackbox.feature tests run against d.o.) as I was seeing similar failures, but they appear to be passing today.
