### ISSUE TITLE
Incompatible with symfony/yaml@3.0

### ISSUE THREAD

**Issue by mathewpeterson** [jhedstrom/drupalextension#225]
Symfony released version 3 which breaks backwards compatibility from 2.

As stated in the [symfony/yaml changelog](https://github.com/symfony/yaml/blob/master/CHANGELOG.md), it is required to quote `@` and ```

The yaml used in this project needs to be updated to reflect the breaking changes.

**Comment by pfrenssen** [comment]
This has been fixed in PR #232 and can be closed. Thanks for the report!
