### ISSUE TITLE
logged in as a user with permission not working?

### ISSUE THREAD

**Issue by morbus** [jhedstrom/drupalextension#227]
Scenario: The custom Ubercart order statuses are added.
    Given I am logged in as a user with the "administer order workflow" permission
    And I am on "admin/store/settings/orders/workflow"
    Then I should see the text "download"
    And I should see the text "shipping"

Results in:

Notice: Undefined property: stdClass::$role in vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/RawDrupalContext.php line 430

and the test fails.

**Comment by morbus** [comment]
The role does appear to be created properly, and assigned to $this->user->roles (based on debugging in assertLoggedInWithPermissions), and that makes it to $this->login(). The actual Notice above is "just" a bug regarding $this->role being used instead of $this->user->roles(), but I'm still unable to figure out why the login (and the rest of the test) is failing.

**Comment by morbus** [comment]
I'm able to confirm that the user, with this created role, is being logged in (by adding print $this->getSession()->getPage()->getContent(); after the $submit->click() inside $this->login()). But, once things get to $this->loggedIn(), it appears the page being returned into $element there, the user is logged out again...

**Comment by morbus** [comment]
If I disable the if (!$this->loggedIn()) check, my test completes fine. Heh.

**Comment by Berdir** [comment]
loggedIn() works by looking for a Logout link. Maybe you don't have that or you renamed it. There are some issues that discuss on how to improve that.

**Comment by morbus** [comment]
@Berdir: It's not that, as I've many other logged-in-user tests working fine, even in the same Feature. I did think it might have to do with the page I'm requesting not having a Logout link on it, but the loggedIn() check moves to / first (which does have a Logout link).

**Comment by morbus** [comment]
Smaller example of working/non-working definitions:

<pre>
  @runonlythis
  Scenario: The custom Ubercart order statuses are added.
    Given I am an anonymous user
    And I am on the homepage
    Then I should see the text "Featured titles"

  @runonlythis
  Scenario: The custom Ubercart order statuses are added.
    Given I am logged in as a user with the "content admin" role
    And I am on the homepage
    Then I should see the text "Featured titles"

  @runonlythis
  Scenario: The custom Ubercart order statuses are added.
    Given I am logged in as a user with the "access content" permission
      Notice: Undefined property: stdClass::$role in vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/RawDrupalContext.php line 430
    And I am on the homepage
    Then I should see the text "Featured titles"
</pre>

**Comment by morbus** [comment]
Alright, I think I figured this out.

"content admin" and "site admin" (two user roles above) get Navbar (per https://www.drupal.org/project/navbar). Navbar has "Log out" in it. The tests are seeing that as a match to $this->getDrupalText('log_out'). However, a user with just a specific permission, above, is not seeing the Navbar and is instead receiving, sigh, "Logout" (sic) as hardcoded in the theme.

i.e., this is all circulating back to exactly what Berdir was saying - "Log out" (Drupal core) was renamed to "Logout" (client-specific theme) and the Navbar module (via it's admin-menu like addition) was confusing things.

Closing.

**Comment by fluxsauce** [comment]
> loggedIn() works by looking for a Logout link.

We're experiencing the same problem on our project, just started with the theme implementation. For context:

```php
  public function loggedIn() {
    $session = $this->getSession();
    $session->visit($this->locatePath('/'));

    // If a logout link is found, we are logged in. While not perfect, this is
    // how Drupal SimpleTests currently work as well.
    $element = $session->getPage();
    return $element->findLink($this->getDrupalText('log_out'));
  }
```

At this point, there really isn't a logout link yet for users other than administrators (who get it through admin_menu). I'm torn, users should be able to log out and it's a problem if they can't, so it'll get fixed regardless.

A more practical approach; make the error contextually appropriate and fix the bug in the error (heh). We rabbit holed on roles when it turns out the actual problem was the missing link.

```
Notice: Undefined property: stdClass::$role in vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/RawDrupalContext.php line 430
```

There's an actual bug, `$role` isn't available for some reason. Therefore, there should be a check for the existence of role before rendering the error.

```php
    if (!$this->loggedIn()) {
      throw new \Exception(sprintf("Failed to log in as user '%s' with role '%s'", $this->user->name, $this->user->role));
    }
```

I think it should say something like

> Cannot determine if logged in because 'log_out' link cannot be found for user '%s'

and then only show

> Cannot determine if logged in because 'log_out' link cannot be found for user '%s' with role '%s'

if role exists.

Please consider reopening.
