### ISSUE TITLE
Guzzle warnings when installing; update to guzzle/guzzle instead of guzzle/*

### ISSUE THREAD

**Issue by aaronbauman** [jhedstrom/drupalextension#229]
Warnings when installing:
"""
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
"""
Which I discovered while trying to solve a separate issue
https://github.com/jhedstrom/drupalextension/issues/228

**Comment by jhedstrom** [comment]
I think this has been resolved.
