### ISSUE TITLE
Add BatchContexts to contexts.html documentation

### ISSUE THREAD

**Issue by morbus** [jhedstrom/drupalextension#240]
A step for "I wait for the batch job to finish" was added here: https://github.com/jhedstrom/drupalextension/commit/a680684cdbed55e3eadaf4205dbc97d2a571ae39

But, it never shows up in the definition lists, and it's considered undefined here:

@api @javascript
Feature: FEATURE_NAME

  Scenario: SCENARIO NAME
    Given I am logged in as a user with the "content admin" role
    And I am on "admin/content"
    And I click "DEFAULT NODE"
    And I click "Edit"
    And I fill in "Series" with "Behat: A compleat work"
    And I press the "Save" button
    And I wait for the batch job to finish

**Comment by jhedstrom** [comment]
You need to manually specify that context in your `behat.yml` file, something like [this](https://github.com/jhedstrom/drupalextension/blob/master/behat.yml.dist#L4-L9).

**Comment by morbus** [comment]
Thanks. Probably needs docs then on

https://behat-drupal-extension.readthedocs.org/en/3.1/contexts.html

**Comment by jhedstrom** [comment]
This is now in the docs.
