### ISSUE TITLE
Anonymous User Session Handling

### ISSUE THREAD

**Issue by winmillwill** [jhedstrom/drupalextension#25]
I'm building a commerce site and I need to be able to test the anonymous checkout case, but in order to do this I need to be able to pass a cookie to the js-aware mink driver after staging a cart with the drupal api, or I guess write up some janky module that makes a path available for an anonymous user to claim the last created cart.

A good intermediary for passing a session ID between drivers like this is not obvious to me. It seems like a bit of a kludge to just stick a sessions array on DrupalContext or the FeatureContext that extends it, but that's all I can see to do.

Moreover, I don't see a good event to react to, because we actually need to do this session trading dance before and after every step....

Is there a better way?

**Comment by jhedstrom** [comment]
I think directly manipulating the session via Mink makes sense if you are manually creating the checkout cart and then need an anonymous user to see that cart in the test.
