### ISSUE TITLE
Is it possible to run the drush driver through terminus/kbox?

### ISSUE THREAD

**Issue by ptmkenny** [jhedstrom/drupalextension#252]
I'm working on Pantheon, which provides `terminus` to facilitate calls to drush (`terminus drush status`) on their servers.  I also am experimenting with [kalabox](https://github.com/kalabox/kalabox), which provides a similar interface (`kbox drush status`).

Is there a way to set the configuration in behat.yml in order to use the terminus or kbox drush instead of the drush on my system?  My system drush cannot do remote access of the pantheon or kbox servers.

**Comment by jhedstrom** [comment]
You can configure the binary when setting up the drush driver, so in theory if you changed it from `drush` to `terminus drush` the commands would work:

Something like this in `behat.yml`:
```yaml
  drush:
    binary: terminus drush
```

**Comment by ptmkenny** [comment]
Awesome, it works in practice, not just in theory-- confirmed with both terminus and kbox.
