### ISSUE TITLE
Composer unable to download Drupal extension 0.1.5

### ISSUE THREAD

**Issue by RoySegall** [jhedstrom/drupalextension#260]
Composer isn't able to download Drupal extension in version 0.1.5 due to:

> Your configuration does not allow connection to http://git.drupal.org/project/drupalextension.git. See https://getcomposer.org/doc/06-config.md#secure-http for details.

I'm using this for OpenScholar and you can see the error [here](https://travis-ci.org/openscholar/openscholar/builds/114469081#L1046)

But when i'm downloading 3.0.0 everything is OK. Thoughts?

**Comment by RoySegall** [comment]
https://github.com/openscholar/openscholar/pull/7744 is dependent on it.

**Comment by jhedstrom** [comment]
Any idea why it's trying to download from drupal.org? Packagist has always pointed at github for the Drupal Extension.

**Comment by RoySegall** [comment]
This is a good question. It suddenly stopped working.

**Comment by jhedstrom** [comment]
Although, testing locally, old versions appear to get pulled from d.o. I may have changed the url from d.o. to github at some point before 3.x. You could force it to pull from github by using the `repositories` part of `composer.json`.

**Comment by RoySegall** [comment]
OK. Cool. I'll try. 10x.

**Comment by RoySegall** [comment]
BTW - solved by [this](https://github.com/openscholar/openscholar/blob/7743/openscholar/behat/composer.json#L2-L6) code of line.
