### ISSUE TITLE
RawDrupalContext::parseEntityFields behaves wrong under PHP 7

### ISSUE THREAD

**Issue by sandervd** [jhedstrom/drupalextension#261]
When in PHP 7 a class is iterated that doesn't implement the Traversable interface (stdClass in this case), it will also iterate over the elements appended to the object while being iterated.
http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.foreach.by-ref

This new behavior causes some trouble:

```
// Replace regular fields inline in the entity after parsing.
if (!$is_multicolumn) {
  $entity->$field_name = $values;
}
```

This will replace the field value with an array, and re-iterate over this field, but now with the array value.
This will then in cause an exeption at
`foreach (explode(', ', $field_value) as $key => $value) {`
as the field value is now an array instead of a string.

**Comment by sandervd** [comment]
PR: #262

**Comment by pfrenssen** [comment]
Fixed in https://github.com/jhedstrom/drupalextension/pull/262.
