### ISSUE TITLE
roleCreate - returning role id or name?

### ISSUE THREAD

**Issue by aronbeal** [jhedstrom/drupalextension#271]
It appears that the Drupal7 driver returns $role->name, but the D8 driver returns $role->id().  Looking at CoreInterface.php, it says:

```
  /**
   * Creates a role.
   *
   * @param array $permissions
   *   An array of permissions to create the role with.
   *
   * @return int
   *   The created role name.
   */
  public function roleCreate(array $permissions);
```

Is it expected that the role name be an integer?  This seems like an error.

**Comment by aronbeal** [comment]
Further perusal shows it's supposed to be a string, so that must just be a typo in CoreInterface.php

**Comment by jhedstrom** [comment]
We should update it to be `int|string`.

**Comment by eknapier** [comment]
https://github.com/jhedstrom/DrupalDriver/pull/153 - new PR for DrupalDriver updates CoreInterface.php and resolves this issue.

**Comment by jhedstrom** [comment]
Thanks @eknapier!
