### ISSUE TITLE
Is there way to debug with xdebug ?

### ISSUE THREAD

**Issue by discipolo** [jhedstrom/drupalextension#274]
i am sure someone can share the proper way to debug tests.
i only found this so far:
https://www.drupal.org/node/2377427#comment-9352091

**Comment by generalconsensus** [comment]
maybe this can help

## XDEBUG Configuration with Phpstorm 
1. On the VM export the following global variables before executing your behat test. 
2. export PHP_IDE_CONFIG="serverName=localhost" && export XDEBUG_CONFIG="idekey=PHPSTORM remote_host=[insert host pc ip address] remote_port=9000"
3. Make sure that Phpstorm is listening for incoming Xdebug connection
4. The Phpstorm Remote Debug window should look like this: https://www.evernote.com/l/AFOIz6c6ZgZH95SMVORHE3PKqzXR3-fHl7MB/image.png
5. The Phpstorm Remote Debug Server window should look like this: https://www.evernote.com/l/AFNq1AfZQjRJ_aWUZt3dsx4jCcjUoB0ldM4B/image.png
6. The Phpstorm Xdebug settings window should look like this: https://www.evernote.com/l/AFNgeZ8wetNEGLbbN1UEhnPmRShsDhXpP9oB/image.png

**Comment by pfrenssen** [comment]
If you have debugging working fine for "normal" code running in the browser, and it mysteriously locks up during test runs, you probably need to increase the number of connections. In PHPStorm this is called 'Maximum simultaneous connections' and can be found in the settings at Languages and Frameworks > PHP > Debug.

I usually set it to 6, but anything between 3 and infinity should do the trick.
