### ISSUE TITLE
Modify existing db objects (feature request)

### ISSUE THREAD

**Issue by aronbeal** [jhedstrom/drupalextension#276]
Hi again,

As far as I can tell, there isn't a way to modify an existing object inserted into the test database.  I'm needing this because I have objects that contain entity references to each other, and my test success depends on both of those references being set.  This turns into a chicken-and-egg problem.

Is Drupal\Driver\Cores\CoreInterface your design?  Would a 'nodeAlter' function be an allowable addition?

**Comment by jhedstrom** [comment]
Would any of the logic here help https://gist.github.com/jhedstrom/5708233?

Since node alter hooks are already called by core, would a testing/fixtures helper module with the alter hooks allow you to achieve what's needed?

I'm open to adding additional methods to `CoreInterface`, but would like an example of how those would be used in step definitions.

**Comment by aronbeal** [comment]
Unfortunately no - I can give the second object created a reference to the first, but not the first to the second.  That example does highlight an aspect of this I wasn't aware of - that being that I have access to drupal function calls within my step tests.  This pretty much solves the problem for me, with the caveat that my solution is no longer generally applicable for inclusion back in the original RawDrupalContext (as I'm making D7 function calls in non-driver files):

```php
  public function nodeAlter($alias, $values) {
    //pay no mind to resolveAlias and convertAliasValues - they serve to 
    //dynamically translate strings to field values at runtime.  Assume static
    //values for purposes of simplicity.
    $node_specs = $this->resolveAlias($alias);
    $values = (object) $values;
    $this->convertAliasValues($values);
    $results = entity_load('node', array($node_specs->nid));
    if (empty($results)) {
      throw new \Exception(sprintf("%s::%s: No nodes found with id %s", get_class($this), __FUNCTION__, $node_specs->nid));
    }
    if (count($results) > 1) {
      throw new \Exception(sprintf("%s::%s: Multiple nodes found with id %s!", get_class($this), __FUNCTION__, $node_specs->nid));
    }
    foreach ($results as $nid => $entity) {
      $e_wrapped = entity_metadata_wrapper('node', $entity);
      foreach ($values as $k => $v) {
        //$old_value = $e_wrapped->{$k}->value();
        // print sprintf("%s::%s: Updating the value of field %s.  Current value: %s, New value: %s\n", get_class($this), __FUNCTION__, $k, $old_value, );
        //if the field is multi-value, transform non-array arguments into an
        //array for the update process.
        if(get_class($e_wrapped->{$k}) === 'EntityListWrapper' && !is_array($v)){
          $v = array($v);
        }
        $e_wrapped->{$k}->set($v);
      }
      $e_wrapped->save();
    }
  }

```
Optimally, I would replace the above with a call to $this->getDriver()->nodeAlter($nid, $values), where the latter would look something like:

```php
  /**
   * Alter an existing node.
   * @param (int/string?) $nid The node id of the node to be modified
   * @param (object/array?) $values An array with field names as keys, and the new values to set for them.
   * @throws (all kinds of crap if something goes wrong)
   */
  public function nodeAlter($nid);
```
As I said, though, I'm sorted for what I'm trying to do, and it's an academic exercise after this point to try to get something generally useful.  You've a lot to be getting on with, I'm sure, so we can close this if you'd prefer to punt for now.

**Comment by aronbeal** [comment]
This issue has been continued in https://github.com/jhedstrom/DrupalDriver/pull/85.  Closing current.
