### ISSUE TITLE
Given a / my :type tests fail when the content type has no body field

### ISSUE THREAD

**Issue by thudfactor** [jhedstrom/drupalextension#282]
Node creation seems to assume every content type has a body field, throwing 

`The field "body" does not exist on entity type "node". (Exception)`

when the content type does not. 

Commenting the 'body' definition from createNode / createMyNode in DrupalContext lets my tests pass …

        $node = (object) array(
             'title' => $title,
             'type' => $type,
             //'body' => $this->getRandom()->string(255),
             'uid' => $this->user->uid,
        );

… but I'm really new to this project and I'm not sure hacking this here is the best place to make the change.

**Comment by aronbeal** [comment]
Howdy @thudfactor,

I'm a very minor contributor to this project so far, without write access, but I've spent a fair amount of time working with it.  The step definitions available in DrupalContext are intended to satisfy the most common use case scenario.  If you want different defaults, you can write your own step definitions that extend RawDrupalContext.

Personally, I think it's worthwhile creating your own where the ones here don't make the cut.  Part of the strength of BDD style testing comes from using your clients' language as part of the test.

A context that would do what you're aiming for here would probably look like:
```php
<?php

use Drupal\DrupalExtension\Context\RawDrupalContext;
use Behat\Behat\Context\TranslatableContext;

/**
 * Provides pre-built step definitions for interacting with Drupal.
 */
class ThudFactorContext extends RawDrupalContext implements TranslatableContext {
  /**
   * Creates content of the given type.
   *
   * @Given I am viewing a/an thudfactor :type (content )with the title :title
   * @Given a/an thudfactor :type (content )with the title :title
   */
  public function createNode($type, $title) {
    // @todo make this easily extensible.
    $node = (object) array(
      'title' => $title,
      'type' => $type
    );
    $saved = $this->nodeCreate($node);
    // Set internal page on the new node.
    $this->getSession()->visit($this->locatePath('/node/' . $saved->nid));
  }
}
```
Note the language change in the step definition doc block that will distinguish it from the original.

**Comment by thudfactor** [comment]
Aron, that makes perfect sense. Thanks for the pointers and the code example, I will give that a try!
