### ISSUE TITLE
guzzlehttp/promises 1.0.3 requires php >=5.5.0

### ISSUE THREAD

**Issue by natgateway** [jhedstrom/drupalextension#284]
Good afternoon!

This morning the following error popped up as composer was installing behat and the drupal extension (using vagrant + ansible). This is for d7.

```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - guzzlehttp/promises 1.0.3 requires php >=5.5.0 -> your PHP version (5.3.10) does not satisfy that requirement.
    - guzzlehttp/promises 1.0.3 requires php >=5.5.0 -> your PHP version (5.3.10) does not satisfy that requirement.
    - Installation request for guzzlehttp/promises 1.0.3 -> satisfiable by guzzlehttp/promises[1.0.3].

FATAL: all hosts have already failed -- aborting

```

My composer.json file is standard, containing the same code outlined in the documentation: 
```
{
  "require": {
    "drupal/drupal-extension": "~3.0",
},
  "config": {
    "bin-dir": "bin/"
  }
}

```
From reading other threads I understand that changing php versions may be coming in the next release, so I was wondering if anyone knew of a workaround in the time being. 

Thank you :)

**Comment by jhedstrom** [comment]
You can work around this by pinning promises to an earlier version in your local `composer.json` file (presumably `1.0.2`?). But in short, supporting older PHP versions is becoming a house of cards, and is mostly about documenting this workaround for now.

**Comment by natgateway** [comment]
Thank you, this worked, but also wanted to mention shortly after I changed composer.json our devops teammate changed our vagrant configs to run php 5.6. With 5.6 running on the box I went back to the default composer json and didn't need to downgrade guzzzle/promises. I wanted to note that here in case anyone else is having similar issues on a vagrant setup.

**Comment by jhedstrom** [comment]
Thanks for the update @natgateway! I'm going to close this out.
