### ISSUE TITLE
Installation docs specify "guzzlehttp/guzzle" : "^6.0@dev"

### ISSUE THREAD

**Issue by jonathanjfshaw** [jhedstrom/drupalextension#285]
http://behat-drupal-extension.readthedocs.io/en/3.1/localinstall.html says
"For Drupal 8, you’ll need to specify the correct version of Guzzle:"
But if I understand right since #202, this has not been necessary.

**Comment by jhedstrom** [comment]
I think that is correct, but have not verified.

**Comment by jhedstrom** [comment]
I think this is resolved now.
