### ISSUE TITLE
UnsupportedDriverActionException not caught

### ISSUE THREAD

**Issue by FatherShawn** [jhedstrom/drupalextension#286]
Really puzzling.  This code in `behat/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/MinkContext.php` is not catching a `Behat\Mink\Exception\UnsupportedDriverActionException`

```
public function pressButton($button) {
    // Wait for any open autocomplete boxes to finish closing.  They block
    // form-submission if they are still open.
    // Use a step 'I press the "Esc" key in the "LABEL" field' to close
    // autocomplete suggestion boxes with Mink.  "Click" events on the
    // autocomplete suggestion do not work.
    try {
      $this->getSession()->wait(1000, 'typeof(jQuery)=="undefined" || jQuery("#autocomplete").length === 0');
    }
    catch (UnsupportedDriverActionException $e) {
      // The jQuery probably failed because the driver does not support
      // javascript.  That is okay, because if the driver does not support
      // javascript, it does not support autocomplete boxes either.
    }

    // Use the Mink Extension step definition.
    return parent::pressButton($button);
  }
```

Which makes no sense to me. Without using a JS enabled browser, this method fails. Can someone suggest a way forward?

**Comment by jhedstrom** [comment]
I'm not sure I follow. The code itself isn't catching that exception and throwing an uncaught exception anyway?

**Comment by FatherShawn** [comment]
Pretty much.  If I run it in xdebug, I never make it back to your catch block.  The exception is thrown in `\Behat\Mink\Driver\CoreDriver::wait` Stepping forward the next execution is `\Behat\Testwork\Call\Handler\RuntimeCallHandler::executeCall() L106` which catches the exception and does not rethrow it.

**Comment by FatherShawn** [comment]
Execution continues as the results are packaged, testing suspended and so on.  I'm usually in #drupal-contribute on IRC if you want to discuss..

**Comment by jhedstrom** [comment]
Feel free to re-open if this is still an issue.
