### ISSUE TITLE
Cannot login due to "No submit button at __"

### ISSUE THREAD

**Issue by bridgewaterrobbie** [jhedstrom/drupalextension#292]
Hi, Im new to using behat so thanks for any help.
I am getting this error whenever I try to use the drupal extension to login as a user, such as:

`Given I am logged in as a user with the "authenticated user" role # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
      No submit button at http://events.techwell.dev/ (Exception)
`

I think this may be due to our login button having an id of "edit-submit", but am unsure how to verify this, and if so how to have the drupal extension know that this is what to click.

Thanks

**Comment by jhedstrom** [comment]
You can configure the login button text if it differs from what core does by default. See https://behat-drupal-extension.readthedocs.io/en/3.1/blackbox.html#override-text-strings.

**Comment by bridgewaterrobbie** [comment]
Thank you @jhedstrom, this solved my issue.

**Comment by leymannx** [comment]
Updated link (until `master` gets renamed): https://behat-drupal-extension.readthedocs.io/en/master/blackbox.html#override-text-strings.
