### ISSUE TITLE
provide some transforms for machine names/random data

### ISSUE THREAD

**Issue by djdevin** [jhedstrom/drupalextension#293]
We have to work with machine and user names a lot in Drupal, so when writing 1000s of tests they'll eventually conflict. Sometimes we copy/paste tests to test slightly different scenarios and have to change all the specific references. "testuserC2456_S1" starts to get old after a while and in most cases, we don't care what that user is called, however we do need to refer back to it.

Tag1 did something in a really old custom context https://github.com/tag1consulting/behat-drupalextension

> [random] - a random 8 character string, every time [random] is used in the script, a new random string is generated.
> [random:1], [random:2], - a way to reference back to used random strings, so that you can put a random string on a form, and then check that it appears somewhere later. [random:1] refers to the last random value, [random:2] refers to the second to last random value.

Maybe drupalextension could provide something similar? Or does it already?

These would be great as it would take a lot of load off of testwriting.

For now I wrote a very simple transform but it could be extended with a static random string cache.

```
  /**
   * @Transform /^rand:machine_name$/
   */
  public function makeRandomMachineName($string) {
    return uniqid();
  }
```

**Comment by djdevin** [comment]
Actually here it is, it's the same format as Drupal random tokens (at least in 7), with a name argument appended.

Example:
[random:hash:md5:stored_name]
[random:hash:sha256]
[random:number]
[random:number:myNumber]

```
  /**
   * @Transform /^\[random:hash:(\w+):(\w+)\]$/
   * @Transform /^\[random:hash:(\w+)\]$/
   * @Transform /^\[random:(number):(\w+)\]$/
   * @Transform /^\[random:(number)\]$/
   */
  public function makeRandomMachineName($hash_type, $name = NULL) {
    static $randoms = array();

    if ($name && isset($randoms[$name])) {
      return $randoms[$name];
    }

    if ($hash_type == 'number') {
      return rand(0, 2147483647);
    }
    else {
      $hash = hash($hash_type, drupal_random_key());
    }

    if ($name) {
      $randoms[$name] = $hash;
    }

    return $hash;
  }
```

**Comment by jhedstrom** [comment]
Interesting idea. I could see this coming in quite handy (usernames in-particular are tricky if created via a form since they have to be manually deleted in an after scenario if the same username is used more than once).

I think this could go into a new context that only handles transforms.

**Comment by jhedstrom** [comment]
I'm working on a project now that uses `<foo>` syntax for random strings. These work in isolation (eg, as a node title in a pipe table), or in a string (`<foo>@example.com`). I'm not tied to the `<>` bit, but perhaps something similar here?
