### ISSUE TITLE
cURL errors when using Drupal driver in TravisCI

### ISSUE THREAD

**Issue by mccrodp** [jhedstrom/drupalextension#294]
I have the cURL error in a build as seen in the [TravisCI build report](https://travis-ci.org/mccrodp/marketo_rest/jobs/147966306) for a D7 module also shown below.

```
Scenario: Site is accessible                              # features/travis-ci.feature:7
    Given I am on the homepage                              # Drupal\DrupalExtension\Context\MinkContext::iAmOnHomepage()
      cURL error 7: couldn't connect to host (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\ConnectException)
```

Is there an alternative to use the API directly in Drupal rather than cURL? i.e. - do we have an equivalent to this [Symfony extension / driver](https://github.com/Behat/Symfony2Extension/blob/master/doc/index.rst) which I believe does not use cURL.

I have tried a few things such as trying different ports in _[travis.yml](https://github.com/mccrodp/marketo_rest/blob/7.x-1.x/.travis.yml)_, setting `base_url` to be of the form `base_url: https://username:pass@example.com` in my _[behat.yml](https://github.com/mccrodp/marketo_rest/blob/7.x-1.x/tests/behat.yml.dist)_ as outlined in this Gist snippet's comment: https://gist.github.com/jhedstrom/5bc5192d6dacbf8cc459#gistcomment-1653821

Any ideas or a link to a working project (in the docs)?

**Comment by jhedstrom** [comment]
Hmm, the curl calls are coming from Mink itself (via the Mink Extension step definitions), and would use the `base_url` you have set in your `behat.yml` file. For steps that do not interact with the browser (eg, `Given content:`, etc), no curl requests should be made. From the `base_url` you have, it looks like you're using http auth. There's this [gist](https://gist.github.com/jhedstrom/5bc5192d6dacbf8cc459) with examples for using that.

**Comment by jhedstrom** [comment]
Feel free to re-open if this is still an issue.
