### ISSUE TITLE
Change in Drupal 8 form ID broke scenario outlines

### ISSUE THREAD

**Issue by mlncn** [jhedstrom/drupalextension#304]
In RawDrupalContext, public function loggedInWithRole($role) is returning true because the user is hanging around (cleanUsers is only deleting from the $this->users array, not the user at $this->user) and the check for $this->loggedIn() incorrectly returns true.

And this function is incorrectly determining if the a user is already logged in because why?  Let's take a look:

```
  public function loggedIn() {
    // [..snipped code..]
    // Some themes do not add that class to the body, so lets check if the
    // login form is displayed on /user/login.
    $session->visit($this->locatePath('/user/login'));
    if (!$page->has('css', $this->getDrupalSelector('login_form_selector'))) {
      return TRUE;
    }
    // [..snipped code..]
  }
```

The default login_form_selector is form#user-login, whereas for us it is form#user-login-form.

Note: If the theme outputs the expected logged_in_selector, the login_form_selector is never tried, so this bug will not surface.

**Comment by jonathanjfshaw** [comment]
I think you can set your own value for login_form_selector in behat.yml:
```
extensions:
  Drupal\DrupalExtension:
    selectors:
      login_form_selector: 'form#user-login-form'
```

**Comment by pfrenssen** [comment]
Yes, that is the correct way of handling this, thanks @jonathanjfshaw !
