### ISSUE TITLE
Migrate support

### ISSUE THREAD

**Issue by czigor** [jhedstrom/drupalextension#308]
Writing behat steps for creating test content for entities with many and complicated fields  can be really cumbersome. Would pull requests on migrate support be considered? Or is there a recommended way to do this already?

**Comment by czigor** [comment]
This kind of already looks to be supported via Drupal\DrupalExtension\Context\DrushContext.

**Comment by lpeabody** [comment]
@czigor There's also this mechanism for importing test content that I've been using successfully for a while. https://www.webomelette.com/content-fixtures-behat-testing-drupal-7

**Comment by czigor** [comment]
Thanks, @lpeabody! Is this different from using drush migrate commands? (Apart from performance, I mean.)
