### ISSUE TITLE
Scenario Outline with logged out user AND multiple roles in one list

### ISSUE THREAD

**Issue by kwoxer** [jhedstrom/drupalextension#317]
So what I would like to have is the following **Scenario Outline**:
 Scenario Outline: Something
    Given I am logged in as a user with the <roles> role
...
    Examples:
      |         roles        |
      | "authenticated user" |
      | "I am not logged in"   |

but this is not possible because `Given I am logged in as a user with the "I am not logged in" role` for sure does not exists.

**So currently it is just possible via:**
 Scenario: Something 1
    Given I am logged in as a user with the "authenticated user" role
...
 Scenario: Something 2
    Given I am not logged in
...

but yeah I would like to test all possible roles in just one list.

Is this somehow possible or do I need to write my own function?

**Comment by kwoxer** [comment]
Maybe just answer me so that I know my issue is not just because I think totally in the wrong way :)

**Comment by pfrenssen** [comment]
Yes I would solve this indeed by writing your own step definition. Something like this:

```
Scenario:
  Given that my authentication status is <status>
  Examples:
    | status    |
    | logged in |
    | anonymous |
```

You can use whatever business language fits your project :)

**Comment by kwoxer** [comment]
Sorry for very late answering this.

Damnit, so there is some own function needed for this. Good to know. Thanks anyway.
