### ISSUE TITLE
Drupal8/CKeditor problem

### ISSUE THREAD

**Issue by Trogie** [jhedstrom/drupalextension#326]
Hello, I'm trying to fill in a text into a CKeditor field. Problem is that CKeditor replaces the textarea with an iframe without name or id, so how do i switch to that iframe.

I found multiple context already to solve the problem. Just would like to know who finds which solution the best? 

And as CKeditor got core in D8 should this context not get support for it?

**Comment by pfrenssen** [comment]
It would indeed be nice to have support for the built-in editor of D8. A PR is more than welcome.

In the meantime it's not too hard to roll this yourself. The trick is to check if you are running in a JavaScript-enabled browser, and then discover the DOM element containing the editor from the field label. Once you have this you can create steps for filling in text and pressing buttons.

Here is an example I have recently created for a client project:

Ref. https://github.com/ec-europa/joinup-dev/blob/develop/web/profiles/joinup/joinup.behat.inc#L735

```
  /**
   * Enters the given text in the given WYSIWYG editor.
   *
   * If this is running on a JavaScript enabled browser it will first click the
   * 'Source' button so the text can be entered as normal HTML.
   *
   * @param string $text
   *   The text to enter in the WYSIWYG editor.
   * @param string $label
   *   The label of the field containing the WYSIWYG editor.
   *
   * @When I enter :text in the :label wysiwyg editor
   */
  public function enterTextInWysiwyg($text, $label) {
    // If we are running in a JavaScript enabled browser, first click the
    // 'Source' button so we can enter the text as HTML and get the same result
    // as in a non-JS browser.
    if ($this->browserSupportsJavascript()) {
      $this->pressWysiwygButton($label, 'Source');
      $this->setWysiwygText($label, $text);
    }
    else {
      $this->getSession()->getPage()->fillField($label, $text);
    }
  }
```

This uses two traits, one that detects if the browser supports JavaScript: [`BrowserCapabilityDetectionTrait`](https://github.com/ec-europa/joinup-dev/blob/develop/tests/src/Traits/BrowserCapabilityDetectionTrait.php), and one that allows to click buttons and enter text in the editor: [`WysiwygTrait`](https://github.com/ec-europa/joinup-dev/blob/develop/tests/src/Traits/WysiwygTrait.php).

Hope this helps getting you up and running.

**Comment by allgood2386** [comment]
@pfrenssen Is there more elaborate documentation anywhere here? I'm having issues with autoloading and getting Trait Not found while trying to implement your solution.

Fatal error: Call to undefined method FeatureContext::getSession() (Behat\Testwork\Call\Exception\FatalThrowableError)

I'm new to the behat driver so I might be missing some configuration code somewhere. Hopefully if most of the work I'm doing here translates over I'd like to do a pr. I'll use this in the future quite a bit.

**Comment by pfrenssen** [comment]
Maybe try to rebuild the autoloader? If that doesn't work then I don't know, it depends on how your project is set up.

    $ composer dump-autoload

**Comment by SurangaPG** [comment]
I had a similar issue. However the user was only allowed a wysiwyg enabled field. So I injected the "value" straight into the ckeditor. Which is on the edge of the behat principles but does do the trick. 

`            if (!$item->isVisible() && $item->getTagName() == 'textarea') {
                    $id = $item->getAttribute('id');
                    $this->getSession()
                      ->executeScript("CKEDITOR.instances[\"$id\"].setData(\"$value\");");
            }
            else {
                $fieldWrapper->fillField($field, $value);
            }
`
Do note that it will technically fail on all textarea not hidden by the wysiwyg.

**Comment by wluisi** [comment]
@allgood2386 I had the same issue you describe. I had to do the following:

Update your composer.json to include a psr-4 for the traits you added.

```  
"autoload": {
    "psr-4": {
       "Drupal\\your_project_name\\": "tests/src"
    },
    "classmap": [
       "scripts/composer/ScriptHandler.php"
    ]
},
```

After this, run
`composer dump-autoload`
