### ISSUE TITLE
Multi login/logout in 1 scenario problem

### ISSUE THREAD

**Issue by Trogie** [jhedstrom/drupalextension#330]
I'm writing a test scenario where I do something as administrator, then log out to verify something anonymous and log back in for something else.

The second login doesn't work.

Looks like the user property should be unset when loggin out.

**Comment by pfrenssen** [comment]
"Doesn't work" is a bit vague, but maybe you are suffering from the bug mentioned in #306. In case you are accessing the user the user in one context and then logging out in a second context, then you won't be able to log in again in the first context. 

Can you maybe try the latest master branch and see if this fixes your problem?

**Comment by Trogie** [comment]
Not really related to my problem I think as I only use the DrupalExtension Drupalcontext:

Basically I do this:
<quote>
Given I am logged in as a user with the "administrator" role
Then I should see the text "Member for"
Given I am an anonymous user
Then I should see an "h1" element
Given I am logged in as a user with the "administrator" role
Then I should see the text "Member for"
<quote>

The second login fails as the drupalcontext still sees the user as logged in...

**Comment by Trogie** [comment]
Well, I solved my problem with making sure the selectors 'login_form_selector' and 'logged_in_selector' are correctly set for my theme. If these selectors are not set the scenario can not succeed because of the mis-synchronization between the browsersession drupal state (anonymous vs authenticated) and the DrupalContext context.
