### ISSUE TITLE
Drupalextension with Behat ~3.2

### ISSUE THREAD

**Issue by Trogie** [jhedstrom/drupalextension#332]
Hello, 

Is there a particular issue why drupalextension can not be installed with behat ~3.2?

The composer.json file has:
    "behat/behat": "~3.1.0-rc2",

Could this become:
    "behat/behat": "~3.1" ?

**Comment by Trogie** [comment]
I saw composer from time to time downgrading my behat version and then later the drupalextension or vice versa...

**Comment by pfrenssen** [comment]
Thanks for the report! We already made a start on fixing this in #324. There are some failures though that need a closer look.
