### ISSUE TITLE
Nestable, easy to define, locations

### ISSUE THREAD

**Issue by jonathanjfshaw** [jhedstrom/drupalextension#333]
We often want to restrict the focus of a particular step to it a particular part of a page (a "location").

Mink has some steps that include locations as part of them, like
'I should see "text" in the "h2" element'
This drupal extension adds a step of 'region' steps that allow users to define locations in natural language in their behat.yml and then use steps like
'I should see "text" in the "h2" element in the "Page footer" region'

These approaches work OK, but they don't scale and extend very well. 

Imagine we want to create a new action like 'pick "fish" from the fancy widget'. Not only do we have to create that basic step, but if we want to locate it in an element, or a region, then we'll have to create extra steps for that too. 

This leads to a maintenance headache off multiplying complexity. This is already the case in the "region" family of steps. They have to redefine all the basic mink steps in an additional "regioned" version.

These complexities make it tempting to use nested css expressions like 
'I see "text" in the ".section-a .content .byline'
But this is a horrible leaking of implementation details into our test steps in violation of BDD principles. 
Doesn't something cringe inside you when you write a step like
'I fill in "test" in the field "field_myfield_target_value[1]" to create a new entity reference in D8?

I suggest that the solution to all this is to create a new way of working with locations that allows _locations_ (fields, blocks, regions, elements) to be defined separately from _actions_ (seeing, filling in, pressing). This removes the multiplying interaction between the 2 and makes it much easier to specify locations in a clean BDD way.

My first stab at this follows:

```
@api
Feature: Basic location example
  In order to explain the idea of nested locations
  I need to give a simple example of som steps

  Scenario: Basic location example
    Given I am logged in as an administrator
    Given I am on the homepage
    Then I should see "Add content" in the ".content" element in the "Tools" block
    Then I should see "Tools" in the heading in the "Tools" block
```

which is made possible by the following context:

```
  /**
   * Allow locating of any element using a css expression.
   * 
   * @Transform /(.*)in the "(.*)" element(.*)/
   *
   * @param string $before
   * @param string $locator
   * @param string $after
   * @return string
   */
  public function elementLocation($before ="", $locator, $after ="")
  {
    return $before . 'in the "' . $locator . '" "css" location' . $after;
  }

  /**
   * Allow locating of named Drupal blocks.
   * 
   * @Transform /(.*)in the "(.*)" block(.*)/
   *
   * @param string $before
   * @param string $locator
   * @param string $after
   * @return string
   */
  public function blockLocation($before="", $locator, $after ="")
  {
    return $before . 'in the "block-bartik-' . $this->stringToClassName($locator) . '" "named:id" location' . $after;
  }

  /**
   * Allow locating of headings.
   * 
   * @Transform /(.*)in the heading(.*)/
   *
   * @param string $before
   * @param string $locator
   * @param string $after
   * @return string
   */
  public function headingLocation($before="", $after ="")
  {
    return $before . 'in the "h1,h2,h3,h4,h5,h6" "css" location' . $after;
  }

  /**
   * Transform complete location argument (possibly containing multiple 
   * sub-arguments) into a NodeElement
   * 
   * @Transform /^in the "([^"]*)" "([^"]*)" location$/
   * @Transform /^in the "([^"]*)" "([^"]*)" location in the "([^"]*)" "([^"]*)" location$/
   * @Transform /^in the "([^"]*)" "([^"]*)" location in the "([^"]*)" "([^"]*)" location in the "([^"]*)" "([^"]*)" location$/
   * 
   * @param string $location1
   * @param string $locationType1
   * @param string $location2
   * @param string $locationType2
   * @param string $location3
   * @param string $locationType3
   * @return array

   */
  public function transformLocations($location1, $locationType1, $location2=NULL, $locationType2=NULL, $location3=NULL, $locationType3=NULL)
  {
    $locations = array();
    $locations[] = $this->getSession()->getPage();
    $currentLocationDescription = 'page ' . $this->getSession()->getCurrentUrl();

    if (!empty($location3)) {
      $locations = $this->getLocations($locations, $locationType3, $location3);
      if (count($locations) === 0) {
        throw new \Exception(sprintf('The "%s" %s location was not found in the %s.', $location3, $locationType3, $currentLocationDescription));
      }
      $currentLocationDescription = '"'. $location3 . '" ' . $locationType3 . ' location in the ' . $currentLocationDescription;
    }
    
    if (!empty($location2)) {
      $locations = $this->getLocations($locations, $locationType2, $location2);
      if (count($locations) === 0) {
        throw new \Exception(sprintf('The "%s" %s location was not found in the %s.', $location2, $locationType2, $currentLocationDescription));
      }
      $currentLocationDescription = '"'. $location2 . '" ' . $locationType2 . ' location in the ' . $currentLocationDescription;
    }
    
    $locations = $this->getLocations($locations, $locationType1, $location1);
    if (count($locations) === 0) {
      throw new \Exception(sprintf('The "%s" %s location was not found in the %s.', $location1, $locationType1, $currentLocationDescription));
    }

    return $locations;
  }

  /*
   * Transform a single location argument into an array of NodeElements by
   * searching within each of the current location(s) for elements matching
   * $locator using the $locatorType search method.
   * @param array $locations
   * @param string $locatorType
   * @param string $locator
   */
  protected function getLocations(array $locations, $locatorType, $locator) {

    // $locatorType can be of forms like
    // "named:id" or
    // "namedExact:content"
    // which are not in themselves valid arguments for ->find and
    // need to be translated into
    // ->find("named", array("id", ...)) and
    // ->find("namedExact", array("content", ...))
    if (substr($locatorType, 0, 5) === "named"){
      $locatorTypeParts = explode(":",$locatorType);
      $locatorType = $locatorTypeParts[0];
      $locator = array($locatorTypeParts[1],$locator);
    }

    $newLocations = array();
    foreach ($locations as $location) {
      $theseLocations = $location->findAll($locatorType, $locator);
      $newLocations = array_merge($newLocations, $theseLocations);
    }
    return $newLocations;
  }


  /**
   * @Then I should see :text
   * @Then /^I should see "([^"]*)" (in the .*)$/
   *
   * @param string $text
   * @param array $locations
   */
  public function assertTextinLocation($text, array $locations = [])
  {
    if (count($locations) == 0) {
      $locations[] = $this->getSession()->getPage();
    }

    $found = FALSE;
    foreach ($locations as $location) {
      $matches = $location->findAll('named', array('content', $text));
        if (count($matches) > 0) {
          $found = TRUE;
          break;
        }
    }
    if (!$found) {
      throw new \Exception(sprintf("Text '%s' not found", $text));
    }
  }
```

This is not on its own very impressive. But it shows a way of defining locations and actions that is very simple and easily expandable, but which allows for extreme flexibility.

The main gotcha that I have found so far is that the transformLocations function must be placed AFTER the other location functions, which is slightly annoying.

I think my regex leave a fair amount to be desired, and I have not tested this much, but I wanted to put it up here for feedback sooner rather than later. 

The main problem I have had has been getting the nesting to work. I have not found a way to get the individual location transformations to be called in the right order, passing the result of the previous location, which would enable the individual location transformations to return a NodeElement. Therefore I've had to instead have them return a kind of encoded string that specifies a precise search location, and then in a final transformation turn that compound string into a NodeElement. It's a bit hacky but it works.

**Comment by pfrenssen** [comment]
This is some amazing stuff, I have never thought of using `@Transform` to actually change the meaning of a step definition, I only ever used it for changing parameters. Thanks a lot for sharing this!

I'm not thinking this is something we can merge into drupal-extension though. First of all it might break backwards compatibility or have unexpected consequences in existing projects that are already using similar steps.

Also, I don't think drupal-extension is the right place for this, this is more something to integrate in behat proper. We are simply an extension for Behat to provide Drupal integration. This functionality is useful for projects written in any framework.

**Comment by pfrenssen** [comment]
Great, I just saw that this is already proposed upstream in https://github.com/Behat/Behat/issues/978

Closing this now, let's continue in the upstream issue.

**Comment by jonathanjfshaw** [comment]
Since posting, I've come to think that the Behat Tokens extension (
https://github.com/asgorobets/TokensExtension) probably offers a cleaner
and more robust way to achieve the same thing.

I agree that fundamentally this belongs upstream, but I suspect that Behat
itself will say that it belongs downstream.

If there was an extension offering this functionality, would you be
interested in offering a context that leveraged it?

Adequate BC can be provided by making sure that nothing takes effect
without the context/extension being added to the behat.yml file explicitly
by the end user; nothing can prevent the possibility of collision with
existing custom steps though, that's an intrinsic problem with aiming for
natural uses of language.
