### ISSUE TITLE
Decide on coding standard

### ISSUE THREAD

**Issue by pfrenssen** [jhedstrom/drupalextension#338]
The project currently uses a mixture of PSR2 and Drupal coding standards. This confusion puts an unnecessary cognitive load on contributors while writing code.

It would be nice to decide on a standard and document this in the README. In a future issue we can then put an automated coding standards check in place and start fixing the coding standards violations.

**Comment by pfrenssen** [comment]
Since this is an extension for the Behat project which uses the PSR2 coding standard my personal preference goes to adopting the PSR2 standard.

**Comment by jhedstrom** [comment]
Good idea--this always bothered me that it was a mix. I'm fine going with PSR2 standard.

**Comment by jhedstrom** [comment]
I've opened #426. I think we need a mix since we have the `fixtures` directory.
