### ISSUE TITLE
Just test specific row of a table via @tag

### ISSUE THREAD

**Issue by kwoxer** [jhedstrom/drupalextension#345]
Is there a way to set a tag on just one row.

So taking this feature here. I just want to set the tag @minimal on Trial role. So when the Testsuite minimal is running it just should test the Trial role. Is this somehow possible via table?

Or just realizable with another Scenario resulting in duplicating the code?

```
  Scenario Outline: Check if exercises are working for all roles
    Given I am logged in as a user with the <roles> role
    ...
  Examples:
  |         roles        |
  | "Flatrate"           |
  | "Trial"              |
  | "Administrator"      |
```

**Comment by pfrenssen** [comment]
I think this is more a question for Behat than for the Drupal extension, can you try posting it at https://github.com/behat/behat/issues ?
