### ISSUE TITLE
Require more specific versions in composer.json

### ISSUE THREAD

**Issue by grasmash** [jhedstrom/drupalextension#35]
I'm currently attempting to add this extension to Drupal 8 core's composer.json, and running into issues with the package versions defined in this project's composer.json.

````
    - Installation request for drupal/drupal-extension dev-master#fad51a12a90f5b7db0cab9f972e8415113bf0222 -> satisfiable by drupal/drupal-extension[dev-master].
    - drupal/drupal-extension dev-master requires behat/mink-extension 2.0.x-dev -> no matching package found.
````

I am assuming this is because:

````
- The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
````

Rather than specifying "*" for behat/mink-extension, it may be better to specify a stable tag. E.g.,
`"behat/mink-extension": "v1.3.3"` or `"behat/mink-extension": "~v1.3.3"`

This update should also be applied to:
````
    "behat/mink-goutte-driver": "*",
    "behat/mink-selenium2-driver": "*",
````

**Comment by jhedstrom** [comment]
Since this is a library, I think leaving the specific versions up to folks using it (eg, specify in their own `composer.json` any specific versions) is going to be preferable here.
