### ISSUE TITLE
Best way to enable test module using Behat

### ISSUE THREAD

**Issue by subhojit777** [jhedstrom/drupalextension#357]
This is more of a **support request**.

I am using Drupal 8. I am writing Behat tests for this [module `listjs`](https://github.com/subhojit777/listjs/tree/8.x-1.x).

I want to enable this test module [`listjs_theme_test`](https://github.com/subhojit777/listjs/tree/8.x-1.x/tests/modules/listjs_theme_test) using this [Behat drush step](https://github.com/subhojit777/listjs/blob/8.x-1.x/tests/features/listjs_theme.feature#L6). But it gives error *`listjs_theme_test` was not found*.

The Behat step was working in Drupal 7. What would be the best way to enable this module in Drupal 8.

Thank you.

**Comment by jhedstrom** [comment]
I'm not able to access the linked behat step. You should make sure the behat step definition is changing into the Drupal directory before trying to enable the module. That would be my guess as to why it's not found. Also, running behat with `--verbose` may produce more information about why it's not finding the module.

**Comment by jhedstrom** [comment]
Closing this out for now, but feel free to re-open for further discussion.
