### ISSUE TITLE
Can we escalate refactoring to work with Behat 3.3?

### ISSUE THREAD

**Issue by lhridley** [jhedstrom/drupalextension#362]
Behat 3.3 (rolled out around Christmas) introduces dependency injection (Yay!) which I could really use in some custom contexts right now.  Any chance we can escalate updating so that we can utilize Behat 3.3?

Looks like Behat 3.3 also drops support for php5.3, with 5.4 and 5.5 to follow shortly.

**Comment by djdevin** [comment]
Looks like there was a refactoring ticket #332 with some discussion about 3.2. I just noticed there are fixes in Behat 3.2+ that I need :(

**Comment by jonathanjfshaw** [comment]
See #382

**Comment by pfrenssen** [comment]
Yes it is now supported in the master branch, this is fixed.
