### ISSUE TITLE
Behat can't find database when using local.settings.php

### ISSUE THREAD

**Issue by ComboPrime** [jhedstrom/drupalextension#373]
For security purposes, I have my Drupal database settings stored in a local.settings.php file outside of the web tree. Drupal has no problem following a require_once statement in the regular settings.php:

// Load local settings file with database settings from security directory if it exists.
define('__SECURITY_DIR__', preg_replace("#Docs/sites/default#i", "Security", __DIR__) ) ;
$local_conf_file_path = __SECURITY_DIR__ . '/local.settings.php' ;

if (file_exists($local_conf_file_path)) {
	require_once($local_conf_file_path);
}

...but Behat chokes with this error:

`[Drupal\Driver\Exception\BootstrapException]                                  
  Missing database setting, verify the database configuration in settings.php.`

Thanks for any help!

**Comment by jhedstrom** [comment]
Perhaps try removing the `file_exists()` conditional and see what the error is. My guess is that since Behat is running in a different directory, the relative path to the file is changing, or something like that.

**Comment by ComboPrime** [comment]
Thanks for the quick response!

Replacing all the above PHP with just these two lines:

$absolute_file_path = '/Users/username/sites/project/Security/local.settings.php' ;
require_once($absolute_file_path);

Still throws the same error ("Missing database setting…"). Not sure what else to try.

**Comment by jhedstrom** [comment]
Did you ever sort this out?

**Comment by ComboPrime** [comment]
> Did you ever sort this out?
> 

Sorry, had to stop work on this project for health reasons.

etg

**Comment by jhedstrom** [comment]
Sorry to hear that. Feel free to re-open this in the future if you need help sorting it out :)

**Comment by JackG102** [comment]
I was having a similar issue when I tried to use the Drupal API Driver feature.  I am running a Docksal environment with a Drupal 9 build, so my solution is somewhat Docksal focused. Oddly enough, without using Drupal API driver everything works, but I need those extra features for testing Drupal.

Similar to above posters, I would inevitably get various CLI errors such as "SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)" or "SQLSTATE[HY000] [2002] Operation timed out", or some kinds of 'Can't connect to DB errors' when trying to run '/bin/behat' or 'bin/behat -di'.  I made a whole host of changes to my local.settings.php, changing the 'host' key to 127.0.0.1 or 'host' to try to solve the issue to success or other environment changes.  As I continued debugging, I felt like I was going about this the wrong way looking at the environment or db 'layers'.

I then decided to change tack and dive deeper into the Docksal documentation on Behat implementation(why didn't I start there?!): [https://docs.docksal.io/tools/behat/](https://docs.docksal.io/tools/behat/)

Long story, short, I got it working using the file structure that Drupal Extension kinda wants with modifying some of the code snippets listed in the Docksal docs, using custom Docksal commands.  I won't lie that I exactly know why this solved the issue, but it seems to have something to do with Docker virtualization...not sure.
  
Let me paste below my code snippets for the various files

behat.yml
Note: I throw in the the 'docker' in the beginning, which will be referenced in a later command the Docksal can use. Also change out my URL for your project's URL
```
docker:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
  extensions:
    Drupal\MinkExtension:
      goutte: ~
      base_url: http://jackblog.docksal  # Replace with your site's URL
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal' 
      drupal: 
        drupal_root: 'web' 
```
My FeatureContext.php is the generic one created by Drupal Extension
```
<?php

use Behat\Behat\Context\Context;
use Behat\Gherkin\Node\PyStringNode;
use Behat\Gherkin\Node\TableNode;

/**
 * Defines application features from the specific context.
 */
class FeatureContext implements Context
{
    /**
     * Initializes context.
     *
     * Every scenario gets its own context instance.
     * You can also pass arbitrary arguments to the
     * context constructor through behat.yml.
     */
    public function __construct()
    {
    }
}
```
This is where the rubber hits the road -- I had to modify/create Docksal commands, which would run my Behat tests or list the available Behat commands, which appeared to solve the issue.

Under the .docksal/commands folder, I created a 'behat' file with the following text that largely came from here([https://github.com/docksal/boilerplate-drupal7-advanced/blob/master/.docksal/commands/behat](https://github.com/docksal/boilerplate-drupal7-advanced/blob/master/.docksal/commands/behat)):

```
#!/usr/bin/env bash

## Run project's Behat tests.
##
## Usage: fin behat [--path=path] [arguments]
##
## path defaults to tests/behat

# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"

params=''
path='features'
for i in "$@"; do
	case "$i" in
		--path=*)
			path="${i#*=}"
			;;
		*)
			params="$params$i "
			;;
	esac;
done

behat_yml_path="./behat.yml"
if [[ ! -f "$behat_yml_path" ]]; then
	echo "Could not find $behat_yml_path"
	exit 1
fi

cd $PROJECT_ROOT

# Launch Behat tests
fin exec "vendor/bin/behat -p docker $params"
``` 
The important parts here are:

-  I told behat.yml lived at the project root: behat_yml_path="./behat.yml"
- The final command executed behat tests with 'docker' profile defined in behat.yml
- To be honest, not sure what '$params" is doing but it came from the code snippet from the cited link above.

I decided as well to create another Docksal command to list all the available Behat commands for writing steps as I can't remember all the Given, When, Then syntax.
I created a file called behat-list in .docksal/commands folder with the following code:
```
cd $PROJECT_ROOT
fin exec "vendor/bin/behat -p docker $params -dl"
```
Now I can type "fin behat" to run my tests or type "fin behat-list" to see all the Given, When, Then options.

Like I said, I won't lie that I understand everything about why this works, but ultimately it was about getting Docksal to play nice.  So if other folks are having issues with Drupal Extension with DB connections in local.settings.php or a similar file, putzing around with that environment's docs and commands might lead to the solution. 

I am very new to Behat and Drupal Extension, just started looking into this week, but I hope this helps folks or get them going with Docksal.
