### ISSUE TITLE
Fix failures on the 3.3 branch

### ISSUE THREAD

**Issue by pfrenssen** [jhedstrom/drupalextension#382]
In preparation of the new 3.3.0 release #324 has been cherry-picked from the master branch onto a new 3.3 branch but this is causing some namespace related failures.

We should fix this so we can make the release.

**Comment by jhedstrom** [comment]
Is this still an issue?

**Comment by jhedstrom** [comment]
I think this is [resolved](https://travis-ci.org/jhedstrom/drupalextension/builds/275163639).
