### ISSUE TITLE
Unable to login with the user created via Drupal Context

### ISSUE THREAD

**Issue by sswarupa2017** [jhedstrom/drupalextension#388]
Hi, I am very new to Behat and Drupal. I have created a user using the step def from Drupal Context

The versions I am using are:  "require-dev": {
                "behat/behat": "^3.0",
                "behat/mink": "~1.7",
                "behat/mink-goutte-driver": "~1.2",
                "drupal/drupal-extension": "^3.2",
                "drush/drush": "8.1.10",

I have @api tag for the scenario
         
 Given I am logged in as a user with the "administrator" role
The step turns green and I am printing the username and password that is randomly generated. When I try to login using the credentials I see the message->
Unrecognized username or password. Forgot your password?

I am using   api_driver: 'drupal'
      drupal: 
        # This must be an absolute path.
        drupal_root: /var/www/xxx/docroot

I am running from vagrant VM on a remote site. 
Pl. let me know if you need more information. Any help will unblock me. 

Also, although the step 'Given I am logged in as a user with the "administrator" role' is green, the steps that follow for validating page elements (from Mink Context) are not working. When I hard code valid username and password then I am able to automate the login flow and validate elements on page using mink context.

**Comment by jonathanjfshaw** [comment]
The user is cleaned up when the scenario ends, so you can't login manually afterwards. You can however pause the scenario using 'Then I break' and try logging in then. I suggest you post you full scenario.

**Comment by sswarupa2017** [comment]
Thank you. I am able to create account and login with using 'Then I break'
