### ISSUE TITLE
iWaitForAjaxToFinish() not really working?

### ISSUE THREAD

**Issue by Berdir** [jhedstrom/drupalextension#400]
At least in D8, the wait for ajax to finish step isn't working and our tests are full of "And I wait 1-3 seconds", which makes them a lot slower than they have to be.

I tried an implementation based on what core uses in \Drupal\FunctionalJavascriptTests\JSWebAssert::assertWaitOnAjaxRequest, which looks a bit like this then:

```
  /**
   * Wait for AJAX to finish.
   *
   * @see \Drupal\FunctionalJavascriptTests\JSWebAssert::assertWaitOnAjaxRequest()
   *
   * @Given I wait for AJAX to finish
   */
  public function iWaitForAjaxToFinish() {
    $condition = <<<JS
    (function() {
      function isAjaxing(instance) {
        return instance && instance.ajaxing === true;
      }
      return (
        // Assert no AJAX request is running (via jQuery or Drupal) and no
        // animation is running.
        (typeof jQuery === 'undefined' || (jQuery.active === 0 && jQuery(':animated').length === 0)) &&
        (typeof Drupal === 'undefined' || typeof Drupal.ajax === 'undefined' || !Drupal.ajax.instances.some(isAjaxing))
      );
    }());
JS;
    $result = $this->getSession()->wait(5000, $condition);
    if (!$result) {
      throw new \RuntimeException('Unable to complete AJAX request.');
    }
  }

```

This is working better, but also not in all cases. I still need to wait manually when e.g. submitting an entity browser widget.

Also not sure if this is 8.x specific.

**Comment by Berdir** [comment]
The merge request was merged, closing this.

**Comment by jochemvn** [comment]
I saw this issue made it in 3.3.1. However now our builds are failing on 'iWaitForAjaxToFinish'. The error is we get is:
```
And I wait for AJAX to finish                                                                                 # SocialMinkContext::iWaitForAjaxToFinish()
      Unable to complete AJAX request. (RuntimeException)
```
Our usecase is that we test uploading a file in a normal image field and we wait for the Ajax process to finish the upload and then we press save. 

Any thoughts on how to fix this? For now I've changed the version back to 3.3.0.

**Comment by Berdir** [comment]
And how long does that take? The exception is thrown if the condition is not true after 5s. Before it just waited and then moved on. We *could* go back to that, but it is likely that this didn't really work either before already, you just didn't get an error

**Comment by alexdesignworks** [comment]
In D7 wait for Ajax was working correctly. 3.3.1 broke it. 3.3.0 works correctly

**Comment by gregj0** [comment]
Now I am getting period failures in Drupal 8 on travis builds with Unable to complete AJAX request.   Would be be possible to use a default of 5 seconds but allow a parameter passed to the constructor to override that with a longer wait time?

**Comment by bramtenhove** [comment]
@Berdir, I just checked the test @jochemvn is referring to. After the upload (and Ajax wait step) we verify that the file is uploaded correctly and accessible.

In 3.3.0 this does work, we do not receive errors nor do we have issues accessing the file.

**Comment by ashwinshmtp** [comment]
We are facing the same issue while upgrading blt-require-dev to 11.x-dev. After upgrading it, the drupal/drupal-extension got updated to v4 and got a "**RuntimeException: Unable to complete AJAX request**" error.
