### ISSUE TITLE
Chromedriver executable not found.

### ISSUE THREAD

**Issue by khareprashant** [jhedstrom/drupalextension#402]
Chrome version: 60
Tried with Chromedriver version 2.30 and 2.31.

**Comment by Trogie** [comment]
Could you give us a little more details please?

I suppose your Selenium doesn't find the chromedriver? Did you put the chromedriver in the same directory as the selenium jar file? Do you start up selenium from another (relative) directory?

**Comment by pfrenssen** [comment]
I'm sorry that you are having trouble but there is no code in this project that deals with chromedriver so this is out of scope for us. The chromedriver integration is part of the Mink project, please take a look at https://github.com/minkphp/MinkSelenium2Driver
