### ISSUE TITLE
Behat context for testing SEO functionality

### ISSUE THREAD

**Issue by sswarupa2017** [jhedstrom/drupalextension#403]
I see that there is an extension for Behat for SEO (https://github.com/M6Web/behat-seo-extension/issues) but not for 3.0. Is there any other extension that is available for 3.0 for testing SEO?

I need to verify the canonical tag from Page Source mainly. Pl. let me know if there are any out of box methods for the same.

**Comment by pfrenssen** [comment]
It seems you have mixed up two projects, this is the Behat extension that provides integration for writing scenarios that interact with the Drupal content management system. We do not have anything to do with SEO.
