### ISSUE TITLE
Breaks around ~20 seconds between scenarios by having ~1.000 nodes SQLite database

### ISSUE THREAD

**Issue by jepster** [jhedstrom/drupalextension#404]
If I have a small SQLite database with 5 nodes, then my Behat tests are running blazing fast. If I setup a database with 1000 nodes, there are always breaks between my Behat scenarios which take around 20 seconds. I am testing with the Chromedriver and there's no visible ongoing page load or wait time after clicking manually. The PHP error log doesn't also present any error. Why Behat behaves suddenly so slow?

**Comment by jepster** [comment]
OK, it looks Behat is executing all actions in the "Background" section before each scenario. I need to find a way to execute some background tasks only once at the beginning of the test feature.

**Comment by aronbeal** [comment]
Hi Jepster,

Have you looked into usage of the [`@BeforeFeature`](http://behat-docs.readthedocs.io/en/v3.0/user_guide/context/hooks.html) tag?  Adding this to one of your active contexts will allow you to execute what you need to before feature execution.

Example usage:
```php
  /**
   * Says hello before every feature.
   *
   * @param \Behat\Behat\Hook\Scope\BeforeFeatureScope $scope
   *   The behat surrounding scope.
   *
   * @BeforeFeature
   */
  public static function beforeFeature(BeforeFeatureScope $scope) {
    print "Hello from " . $scope->getName() . "\n";
  }
```

**Comment by jepster** [comment]
Yeah, I had overlooked this. Thanks.

**Comment by pfrenssen** [comment]
Great that you got it solved, thanks @aronbeal for the suggestion!
