### ISSUE TITLE
3.3.1 #401 breaks ajax-wait for Drupal 7

### ISSUE THREAD

**Issue by BramDriesen** [jhedstrom/drupalextension#412]
When using 3.3.1 and using the Ajax-wait function, it's no longer working.

`And I wait for AJAX to finish                                                         # Drupal\DrupalExtension\Context\MinkContext::iWaitForAjaxToFinish()
      unknown error: Cannot read property 'some' of undefined
        (Session info: chrome=61.0.3163.91)
        (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 6.1.7601 SP1 x86_64) (WebDriver\Exception\UnknownError)`

When locking the composer.json to 3.3.0 it's working fine. Please either roll back the change, or fix the issue. I have no idea what's wrong with it.

**Comment by Berdir** [comment]
There is already https://github.com/das-peter/drupalextension/pull/1 but apparently that was created in the wrong Repo, can you test that?

**Comment by alexdesignworks** [comment]
I can confirm that this is an issue.

@Berdir can we get that PR applied here?

**Comment by das-peter** [comment]
@Berdir Thanks for the ping. Created proper pull request here: #414 
Sorry for being a moron and delaying this with my github incompetence ;)
