### ISSUE TITLE
Why so ambiguous name?

### ISSUE THREAD

**Issue by adriadrop** [jhedstrom/drupalextension#416]
I am wondering why is so ambiguous name chosen? I was really confused at first what is this "drupal extension" like somebody called library "drupal module" or "drupal feature". I just seems like a bad practice to do so.

**Comment by jhedstrom** [comment]
In the Behat world, most add ons are called 'Foo Extension'. See https://github.com/topics/behat-extension.

**Comment by adriadrop** [comment]
There is a difference, 

Symphony
"name": "behat/symfony2-extension"
https://github.com/Behat/Symfony2Extension/blob/master/composer.json

Mink
 "name": "behat/mink-extension",
https://github.com/Behat/MinkExtension/blob/master/composer.json
...
etc 

Most of them if not all have BEHAT in the name, this is for drupal

"name": "drupal/drupal-extension",

So when you end up looking at composer.json you don't have a clue what it is about. Just think it should have a name like,

**"name": "drupal/behat-drupal-extension"**

so new users have it easer time understanding what is what.

**Comment by pfrenssen** [comment]
We are an extension for Behat, not for Drupal. So this follows the naming convention of all Behat extensions.
