### ISSUE TITLE
The reserved indicator "%" cannot start a plain scalar

### ISSUE THREAD

**Issue by IT-Cru** [jhedstrom/drupalextension#453]
This error occurs from some entries in services.yml file in src/Drupal/DrupalExtension/ServiceContainer/config folder. Perhaps more files exists, where this should be fixed.

This seems to be fixed in 3.4 branch, but last tagged v3.4.0 does not include this. Is it possible to tag a new release for this (for example: v3.4.1)?

**Comment by jhedstrom** [comment]
I've added release `3.4.1`. Thanks for the reminder!
