### ISSUE TITLE
Feature Request: "Log in as User 1" Step Definition

### ISSUE THREAD

**Issue by jbickar** [jhedstrom/drupalextension#454]
Hello,

I have searched and not found a "Given I log in as User 1" step definition.

1. Does this exist somewhere, and I'm just missing it? If so, where?
2. If it does not, would you be interested in a PR if I were to write a step definition for it? I was planning to try to create it for our internal work but thought that it might be more generally useful.

**Comment by jhedstrom** [comment]
Does `Given I am logged in as an "Administrator"` not achieve the same thing?

I'd be hesitant to add that step here, but it would be fairly straightforward to achieve in a custom feature context...

**Comment by jbickar** [comment]
No, 'Given I log in as a user with the "administrator" role' is different; User 1 is "special" and has even more power than "administrator" users (specifically around PHP permissions).

I will implement it in our custom feature context. Thanks for the quick reply!

**Comment by pfrenssen** [comment]
I also think this is something that better fits as a custom step definition. Logging in as the super admin is not something that is typically done by end users but is mainly intended for site builders and developers. That is out of scope for most BDD workflows.

Thanks for linking your PR where you implemented this! It can serve as a handy example for others that might be looking for the same.
