### ISSUE TITLE
RawDrupalContext::$user property has been deprecated. 

### ISSUE THREAD

**Issue by Ant63** [jhedstrom/drupalextension#456]
Running in most recent DrupalVM. I'm not sure if this is a miss match of versions issue. This is my config.

`default:
  suites:
    web_features:
      paths: [ features/web ]
      contexts:
        - WebContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      javascript_session: selenium2
      selenium2:
        wd_host: http://newfce.mmt:4444/wd/hub
        browser: chrome
        capabilities: { "browser": "chrome", "version": "*", 'chrome': {'switches':['--start-maximized', "--headless", "--disable-gpu", "--no-sandbox"]}}
      base_url: http://newfce.mmt
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: '/var/www/drupalvm/drupal/forestryengland/docroot'
      region_map:
        title_region: ".region-page-title"
        banner: ".l-hero-banner"
        content: ".region-content"`

Full error message

16384: Interacting directly with the RawDrupalContext::$user property has been deprecated. Use RawDrupalContext::getUserManager->getCurrentUser() instead. in /home/vagrant/.composer/vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/RawDrupalContext.php line 146

Behat Version 3.4.3
Drupal extension installed with compose "drupal/drupal-extension": "*" in build of VM.

**Comment by jhedstrom** [comment]
You should be able to disable this error by setting php to ignore deprecated notices (`E_ALL & ~E_DEPRECATED` in `php.ini` or similar), or convert the code directly accessing `$this->user` to utilize the user manager (`$this->userManager->getCurrentUser()`). The later would be preferable since in future versions these properties will be protected or perhaps even removed...

**Comment by jhedstrom** [comment]
Also, if you run with the `--verbose` flag it should give you a stack trace so you can figure out where the code is that is accessing these properties.

**Comment by jhedstrom** [comment]
Please re-open if this doesn't resolve the issue for you.
