### ISSUE TITLE
Sharing reusable code with the Behat Drupal Extension community

### ISSUE THREAD

**Issue by pfrenssen** [jhedstrom/drupalextension#465]
I want to discuss what would be a good way to share code related to Behat Drupal Extension with the wider community.

I feel that the scope of Behat Drupal Extension itself should stay pretty focused on being the integration between Behat and Drupal. A framework that can be used to successfully apply the BDD principle of solving business communication using a domain specific language. Having step definitions that are Drupal-specific is obviously a part of this, but I don't think that the goal of DrupalExtension should be to provide the largest possible set of step definitions that cater to every little thing that is possible in Drupal.

Building and maintaining these step definitions is very labor intensive since they need to work with all current (and future) versions of Drupal. Secondly, the pre-built steps provided by Drupal Extension are using Drupal-specific terminology, and these do not necessarily match with the domain specific language of a client project. For example, what in Drupal is called "Taxonomy terms" might be called "Tags" by a client, requiring the provided steps to be overridden.

To get to the point, I would like to figure out what would be the best way to share code that is related to Drupal Extension but doesn't necessarily belong inside it. In one of our projects we have started to move the bulk of the logic out of the step definitions into reusable traits. This helps to keep the step definitions, which are domain specific and difficult to reuse across projects, light and easy to write.

Would it be a good idea to start a repository containing reusable traits? Or maybe even start a project on Github similar to [FriendsOfBehat](https://github.com/FriendsOfBehat) that can contain multiple repositories of small reusable projects?

One example I would like to provide is support for interacting with the WYSIWYG. This is something that is hard to do inside Drupal Extension, because only starting with Drupal 8 there is a standard (CKEditor). It is also something that is widely used and difficult to figure out.

https://github.com/ec-europa/joinup-dev/blob/develop/tests/src/Traits/WysiwygTrait.php

**Comment by jhedstrom** [comment]
Great idea! I've for years wanted to move these projects out of my own namespace and follow in the something like Friends of PHP or Friends of Behat.

Once something like that is done, we could allow new contexts to be added outside of the main Drupal Extension. Folks could either use these directly by requiring them via composer, or simply use them for inspiration in writing their own custom contexts.

**Comment by pfrenssen** [comment]
I love this idea! The namespace could be simply 'drupalextension/drupalextension', or maybe 'drupal-bdd/drupalextension'?

**Comment by aronbeal** [comment]
Out of curiosity, what's the primary way people find Drupalextension? I
like the concept, but I'm wondering how discoverability would work.

Searching for "drupalextension" on packagist yields multiple results
(admittedly with the downloads on one far outweighing the others), but how
would a contributor distinguish between his steps, which need
drupalextension, from another package which is a fork of the same?

**Comment by pfrenssen** [comment]
@aronbeal I have no hard data on this but I think most people come here through the project page on Drupal.org: https://www.drupal.org/project/drupalextension

**Comment by pfrenssen** [comment]
Related to this, I just set up an organisation to host projects which are related to Behat but not Drupal: https://github.com/LoversOfBehat/

I was prompted to do this since I made a Behat extension to handle HTML5 tables and I asked permission to the FriendsOfBehat to host this repository, but none of their maintainers has answered my emails. It have the feeling FriendsOfBehat is not accepting outside contributions.

**Comment by pfrenssen** [comment]
@jhedstrom shall we move forward with creating the organisation? Would you be OK with calling it `drupalextension/drupalextension`?

We already have experience with moving repositories to different organisations. It works pretty seamlessly both on Github and Packagist. People accessing the old git repositories will be automatically forwarded to the new one and are notified in the terminal.

**Comment by jhedstrom** [comment]
@pfrenssen I've also had https://github.com/drupaltest as an organization for some time now. The name is so boring, but I don't have too many creative ideas at this point

**Comment by pfrenssen** [comment]
I like that, since it can be about more than just Behat. This means that the idea of putting test traits in a shared repository would fit really well in this organization, because these traits can be used outside of Behat as well in other testing frameworks.

Are you OK if we start working on a drupal-test-traits repository?

**Comment by jhedstrom** [comment]
I've made you and owner, so let's move ahead with it!

**Comment by pfrenssen** [comment]
Great, we'll go ahead with this very soon, we have a ticket in the next sprint to start working on these traits. Thanks!
