### ISSUE TITLE
Log user in on the backend during login steps

### ISSUE THREAD

**Issue by jhedstrom** [jhedstrom/drupalextension#488]
Many modules, and services utilize the `current_user` service for determining ownership, etc. When these hooks or services are called from the backend (for instance, during `Given I am viewing my node...`), `current_user` will be the anonymous user on the backend.

It would be good to have the login and logout steps log the user in on the backend (for the Drupal driver).

**Comment by claudiu-cristea** [comment]
I wonder if we can avoid at all logging in via the form and do direct login via API. That would be a big performance improvement as we don't need to test on each login the form. But I don't see a way to do that.
