### ISSUE TITLE
Please make sure where to report issues

### ISSUE THREAD

**Issue by clemens-tolboom** [jhedstrom/drupalextension#50]
It is currently a skitzo experience where to work on the project.

I prefer GitHub as that supports PRs

But that https://www.drupal.org/project/drupalextension should be closed for new issues

De documentation on d.o is not branch related so that is a wtf too. See my latest PRs

What are your plans?

**Comment by eliza411** [comment]
I think this is close-able. The major adjustment I've made is a commitment to more frequent review with a bare minimum of once a month.

**Comment by clemens-tolboom** [comment]
I know where to go. Thanks
