### ISSUE TITLE
Basic auth support

### ISSUE THREAD

**Issue by andypost** [jhedstrom/drupalextension#531]
I'm trying to use framework on staging site which is protected with basic-auth at nginx level

Googled recipes but nothing works, any idea how to solve it?

**Comment by jhedstrom** [comment]
We used to have this baked in, but realized it could be done in a separate context once Behat 3 allowed multiple contexts.

Here's some docs: https://gist.github.com/jhedstrom/5bc5192d6dacbf8cc459

**Comment by jhedstrom** [comment]
I've also seen it done by just setting the auth in the `base_url` in `behat.yml`, something like:

```
extensions:
  Drupal\MinkExtenstion:
    base_url: https://user:pass@server.com
```

**Comment by jhedstrom** [comment]
Feel free to re-open if those don't work.

**Comment by andypost** [comment]
Thanks, `sed` works like https://github.com/skilld-labs/skilld-docker-container/blob/master/Makefile#L234
