### ISSUE TITLE
I run drush search-api-index -> undefined context

### ISSUE THREAD

**Issue by siva01c** [jhedstrom/drupalextension#532]
We are using behat for testing.  If i wrote "And I run drush cr", it works fine, but if I try  "And I run drush search-api-index " it return question, which context I want use. Every choice is bad choice. 

`/**
    * @Then I run drush search-api-index
    */
   public function iRunDrushSearchApiIndex()
   {
       throw new PendingException();
   }

 [foreach] /var/www/html/phing/tasks/tests.xml:124:8: /var/www/html/phing/tasks/tests.xml:154:12: /var/www/html/phing/tasks/tests.xml:158:26: One or more Behat tests failed.

BUILD FAILED/var/www/html/phing/tasks/tests.xml:20:31: Execution of the target buildfile failed. Aborting.`

How I can run drush commands from modules?  I am using drush 9 on Drupal 8.

**Comment by jhedstrom** [comment]
Hmm, what question is it asking? I'm not sure I understand the issue.

**Comment by jhedstrom** [comment]
Oh, I see--it's not finding the existing step, and offering the function to create a new one. Can you post the output when run with `--verbose`?

**Comment by siva01c** [comment]
I found how where is problem.

**And I run drush sapi-i**  -> doesn't work
**And I run drush 'sapi-i'** -> it works

**Comment by jhedstrom** [comment]
Ah, good find :)
