### ISSUE TITLE
Errors with Chromedriver 75

### ISSUE THREAD

**Issue by danepowell** [jhedstrom/drupalextension#535]
When our CI environments updated from Chromedriver 74 to 75, many tests started failing due to errors being thrown by Curl and Chromedriver.

At least one of these failures is explicitly on a step provided by Drupal Extension, assertLoggedInWithPermissions: https://travis-ci.com/acquia/blt/jobs/206614346

It's possible this isn't necessarily a bug in Drupal Extensions but something else upstream, but Drupal Extension is the next step up the chain from us 😄 At the very least, this is going to soon start affecting a lot of Drupal Extension users, and should probably be documented.

**Comment by jhedstrom** [comment]
Could you run those failing steps with the `--verbose` flag for behat? That should print a stack trace that might help pin-point the issue. My guess is that this particular step fails because it's the first step to make a web request, so it's most likely not specific logic in this step.

This is the error from the travis run (for those searching)

```
 Webdriver http error: 400, payload :{"value":{"error":"invalid argument","message":"invalid argument: missing command parameters","stacktrace":"#0 0x5571b4b4b299 \u003Cunknown>\n"}} (WebDriver\Exception\CurlExec)
```

**Comment by danepowell** [comment]
One stack trace, coming right up: https://travis-ci.com/acquia/blt/jobs/207117420#L3049

Ah, you are right, it's all of the tests tagged as `@javascript` that are failing. So probably not specific to this step.

**Comment by danepowell** [comment]
It looks like this is being addressed in the Mink driver: https://github.com/minkphp/MinkSelenium2Driver/issues/293#issuecomment-499405228

There's also a Chrome bug that may be preventing the workaround described in that issue (disabling w3c) from working: https://bugs.chromium.org/p/chromedriver/issues/detail?id=2943

Feel free to close this in favor of those issues.

**Comment by leymannx** [comment]
Login features are working for me again when adding `extra_capabilities` to `selenium2` to default `w3c: false` as suggested in https://github.com/minkphp/MinkSelenium2Driver/issues/293#issuecomment-499458269

      selenium2:
        wd_host: http://drupal.localhost:4444/wd/hub
        capabilities:
          marionette: true
          browser: chrome
          extra_capabilities:
            chromeOptions:
              w3c: false

Unfortunately clicking (buttons) still doesn't work that way.

**Comment by jhedstrom** [comment]
Closing for now since this appears to be an upstream issue.
