### ISSUE TITLE
SnippetAcceptingContext is deprecated

### ISSUE THREAD

**Issue by danepowell** [jhedstrom/drupalextension#537]
I followed the local installation instructions here: https://behat-drupal-extension.readthedocs.io/en/3.1/localinstall.html

When I initialized Behat, it generated a FeatureContext.php that looks like the template in those docs.

The problem is that my deprecation tests immediately exploded because that class implements SnippetAcceptingContext, which as been deprecated for a few years now: https://github.com/Behat/Behat/pull/922

I'll be the first to admit I'm not super familiar with snippets are/should be handled, but it seems like the docs and code should be revised to not generate deprecated code.

**Comment by jhedstrom** [comment]
Thanks for reporting this!
