### ISSUE TITLE
Call to undefined method FeatureContext::getMainContext()

### ISSUE THREAD

**Issue by pharitz** [jhedstrom/drupalextension#559]
Hi,

 I am trying to access functions in the Behat\MinkExtension\Context\MinkContext class from my FeatureContext.

According to: 
https://github.com/jhedstrom/drupalextension/issues/113
That's not possible :(

But according to this documentation there is another way.
https://docs.behat.org/en/v2.5/guides/4.context.html#communications-between-contexts

I can create an alias for the MinkContext in the FeatureContext's construct function:
```
  public function __construct() {
    $this->useContext('minkcontext_alias', new MinkContext());
  }
```

but when I try to access the MinkContext methods like this:
`$this->getMainContext()->getSubcontext('minkcontext_alias')->some_method();`

But I get this error:
Error: Call to undefined method FeatureContext::getMainContext()

I guess because RawDrupalContext does not extent the base class Behat\Behat\Context\BehatContext.

Why is that? Do you know how I can get around this?

**Comment by pfrenssen** [comment]
Is your `FeatureContext` extending `RawDrupalContext`? If so you can call `$this->getContext('\Behat\MinkExtension\Context\MinkContext')` to access it.

**Comment by jhedstrom** [comment]
If your context needs access to another context, in Behat 3 and beyond, this is the general approach for getting those:

```php
  /**
   * @BeforeScenario
   */
  public function gatherContexts(BeforeScenarioScope $scope) {
    $environment = $scope->getEnvironment();

    $this->drupalContext = $environment->getContext('Drupal\DrupalExtension\Context\DrupalContext');
    $this->minkContext = $environment->getContext('Drupal\DrupalExtension\Context\MinkContext');
  }
```

Above code taken from [here](https://behat-drupal-extension.readthedocs.io/en/3.1/subcontexts.html#for-contributors).

**Comment by pharitz** [comment]
Great, the gatherContexts function works a treat. Thank you!
