### ISSUE TITLE
The testsuite setup should be improved

### ISSUE THREAD

**Issue by stof** [jhedstrom/drupalextension#58]
Currently, the Behat testsuite is done in a weird way (to be honest, Symfony2Extension was done this way as well until I rewrote it for 2.0, and MinkExtension is still done this way): it does not test the extension. It runs a feature suite against drupal and expects it to pass (meaning we cannot test for failure conditions, and https://github.com/jhedstrom/drupalextension/blob/6eb75ba89ab1184f7b6d3a07ef4b33abca04d1bf/features/drush.feature#L20 is really weird and does not fail but marks the test as pending).
Instead, the feature suite should test the DrupalExtension itself (and so for instance the DrupalExtension should probably not be registered in the behat.yml of its own feature suite, as this extension is about testing a Drupal app and you would not be testing a Drupal app but a Behat extension). You can have a look at Symfony2Extension for a better way to do it

**Comment by jhedstrom** [comment]
I think the current test coverage is in a pretty good place. Closing this issue for now, but I would always accept new PRs that increase or improve coverage!
