### ISSUE TITLE
Step annotation syntax error: Given I am logged in as a user with the :role role(s) and I have the following fields

### ISSUE THREAD

**Issue by sensespidey** [jhedstrom/drupalextension#580]
I was having trouble getting a step of the form `Given I am logged in as a user with the :role role and I have the following fields:` to run, and Behat would helpfully offer to create a snippet for me, even though there is already a `function assertAuthenticatedByRoleWithGivenFields` in DrupalContext.php.

I discovered that the  `role(s)` part of the annotation is the problem, specifically the parentheses, which I gather are messing up with the regex matching or something. Changing the annotation to:

`@Given /I am logged in as a user with the :role role and I have the following fields:`

and adjusting the corresponding step to remove the `(s)` allows it to work perfectly.

**Comment by pfrenssen** [comment]
The parentheses are supported by Behat, see the documentation at [Defining steps](https://docs.behat.org/en/latest/quick_start.html#defining-steps).

Both the code that matches steps to code, and the code that generates the snippets are from the Behat project, not in Drupal Extension. I think the best way to get this fixed would be to report it in [the Behat project](https://github.com/Behat/Behat).

**Comment by jhedstrom** [comment]
Closing this out as it looks like it got sorted.
