### ISSUE TITLE
Configure PR tests via Travis on this repository

### ISSUE THREAD

**Issue by xurizaemon** [jhedstrom/drupalextension#593]
I've submitted a PR at #592 and I see that tests for the branch have passed over on TravisCI (on my own account) at https://app.travis-ci.com/github/xurizaemon/drupalextension/builds/231764230

But, I don't see this indicated on the PR, and this seems like useful information to surface there.

I expect this requires either the submitting repository having a TravisCI account set up, or the target repository configuring Travis for PRs (possibly after some initial PR check to prevent abuse).

For now, I'll manually add a link to my PRs, but I figured it won't get improved if no-one asks :)

cc @jhedstrom @pfrenssen (hope the ping is OK!)

**Comment by pfrenssen** [comment]
Thanks for making this issue. We had Travis CI set up, but it seems like the integration is now broken. This possibly happened when Travis CI unified their previously separate open source and commercial offerings.

We probably need to follow the instructions at https://docs.travis-ci.com/user/migrate/open-source-repository-migration/ to re-enable testing. @jhedstrom I think you are the only one who has the privileges to do this?

**Comment by jhedstrom** [comment]
This should be working now. Thanks for opening this!
