### ISSUE TITLE
Add a .readthedocs.yml configuration file

### ISSUE THREAD

**Issue by jhedstrom** [jhedstrom/drupalextension#648]
See https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by jhedstrom** [comment]
@tarunsamanta2k20 please do! I think if you just add the basic config file from that link in a PR it should work. There's also the issue over at https://github.com/jhedstrom/DrupalDriver/issues/266 if you want to do the same there!

**Comment by tarunsamanta2k20** [comment]
@jhedstrom I have already added that file. Have you reviewed my commit?

**Comment by jhedstrom** [comment]
@tarunsamanta2k20 I missed that entirely :) Thanks for working on that!
