### ISSUE TITLE
Drupal 11 support

### ISSUE THREAD

**Issue by jurgenhaas** [jhedstrom/drupalextension#669]
There are a few constraints for dependencies, that prevent us from installing that for Drupal 11, which will be published in a few weeks.

Are there any plans to add support for D11?

**Comment by jhedstrom** [comment]
@jurgenhaas indeed. Do you know what those constraints are?

**Comment by jurgenhaas** [comment]
It's mainly Symfony 7 and all related dependencies. Once that's in place, this package should be required in the context of a Drupal 11 beta installation to see, if any other dependencies may have conflicts.

**Comment by szeidler** [comment]
There is a pull request available now #677 @jhedstrom

**Comment by jhedstrom** [comment]
I think this is done. Thanks all!
