### ISSUE TITLE
Test for a 403 HTTP response code

### ISSUE THREAD

**Issue by jurgenhaas** [jhedstrom/drupalextension#84]
The following scenario should test that node/add can not be accessed:

```
  Scenario: Anonymous user should not be able to add a node
    Given I visit "/"
    When I visit "node/add"
    Then I should get a "403" HTTP response
    And I should see the text "Access denied"
```

Running behat with drupal-extension version 1.0.5 outputs "Current response status code is 403, but 200 expected." and skips subsequent steps.

Changing the scenario into:

```
  Scenario: Anonymous user should not be able to add a node
    Given I visit "/"
    Then I should get a "403" HTTP response
    And I should see the text "Access denied"
```

then I get "Current response status code is 200, but 403 expected.". Almost feels like a catch 22.

What is the correct way of testing this?

**Comment by jonpugh** [comment]
Sometimes I want to check a link click instead of load by URL.  It would be useful to maybe have a second step like: 

> When I click "Test Link" the response status code should be 401

**Comment by pfrenssen** [comment]
@jonpugh that is way too granular to be included in DrupalExtension. We don't plan on combining different steps in a single line, that would just add bloat to the project.

Our scope is just to provide basic support for Drupal specific elements that people can extend with their own step definitions. Link and HTTP response codes are not specific to Drupal so this doesn't belong here.

**Comment by jhedstrom** [comment]
Note that we do already have a step, though it is for direct path access, that does check to ensure a 200 response:

```php
  /**
   * Visit a given path, and additionally check for HTTP response code 200.
   *
   * @Given I am at :path
   * @When I visit :path
   *
   * @throws UnsupportedDriverActionException
   */
    public function assertAtPath($path)
    {
        $this->getSession()->visit($this->locatePath($path));

        // If available, add extra validation that this is a 200 response.
        try {
            $this->getSession()->getStatusCode();
            $this->assertHttpResponse('200');
        } catch (UnsupportedDriverActionException $e) {
            // Simply continue on, as this driver doesn't support HTTP response codes.
        }
    }

```

This  could be used as a starting point in custom contexts for a link-checking step definition that @jonpugh describes.
