### ISSUE TITLE
BeforeStep and AfterStep no longer support tags in Behat 3

### ISSUE THREAD

**Issue by cboyden** [jhedstrom/drupalextension#92]
Tags can no longer be used on BeforeStep and AfterStep hooks. This means that this code in MinkContext.php:

```
/**
   * For javascript enabled scenarios, always wait for AJAX after clicking.
   *
   * @AfterStep @javascript
   */
  public function afterJavascriptStep($event) {
    $text = $event->getStep()->getText();
    if (preg_match('/(follow|press|click|submit)/i', $text)) {
      $this->iWaitForAjaxToFinish();
    }
  }
```

is failing silently - the function is never called.

See https://github.com/Behat/Behat/issues/650 and https://github.com/Behat/Behat/issues/653.

**Comment by jhedstrom** [comment]
This could be fixed by getting the scope from the event, and then checking for the `@javascript` tag.
