### ISSUE TITLE
Testing multilingual sites

### ISSUE THREAD

**Issue by jurgenhaas** [jhedstrom/drupalextension#93]
Using 3.0 of the Drupal Extension I recently ran into trouble with a client's site which is multi-lingual. It happens that basic tests are failing because e.g. content or error messages no longer match the tests when the tests are written in English and the site defaults to German.

I was trying to change the base URL in behat.yml of the project to http://www.exampl.com?language=en which is a valid URL that forces the site to switch to the English context, but that breaks the tests as well as they then seem to be appending the path like "/user" to the base URL which then makes that http://www.exampl.com?language=en/user which is no longer valid.

I wonder what's the best approach here. We could either support queries in the base URL, then the approach like desribed above would already work, or there might be a new setting in the behat.yml that forces the site to a certain context or sends HTTP headers that help to set the language context. Maybe that's already possible and I just haven't found it?

**Comment by jhedstrom** [comment]
Closing this out for now. Let's open new issues to further this along. Thanks!
